/**
 * ground.ts — shared machinery for the Bun-grounding pipeline.
 *
 * Truth hierarchy (P0+P1 refactor, see docs/BUN_GROUNDED.md):
 *   1. pinned bun-types@1.4.0, TS-parsed structurally -> tools/bun-shape.json
 *   2. official bun.com docs (llms.txt-indexed; URLs validated live)
 *   3. consolidated probe registry (tools/ground-probes) — runtime assertions
 * The manifest (tools/bun-grounding.json) and docs/BUN_GROUNDED.md are
 * GENERATED by `bun run ground`; `bun run ground:check` verifies them live.
 * Never hand-edit generated outputs.
 */

// ── shape (pinned bun-types, TS-parsed) ─────────────────────────────────────

export interface ShapeMember {
  name: string;
  ns: string;
  kind: string;
  typeOnly: boolean;
  docs: boolean;
  deprecated: boolean;
  extension: boolean;
}

export interface BunShape {
  bunVersion: string;
  bunRevision: string;
  pinnedVersion: string;
  generatedAt: string;
  members: ShapeMember[];
}

export const SHAPE_PATH = "tools/bun-shape.json";
export const MANIFEST_PATH = "tools/bun-grounding.json";
export const GROUNDED_DOC_PATH = "docs/BUN_GROUNDED.md";
export const DOCS_INDEX = "https://bun.com/docs/llms.txt";

export async function loadShape(root: string): Promise<BunShape> {
  return (await Bun.file(root + "/" + SHAPE_PATH).json()) as BunShape;
}

export function shapeLookup(shape: BunShape): Map<string, ShapeMember> {
  const m = new Map<string, ShapeMember>();
  for (const member of shape.members) {
    m.set(member.ns ? member.ns + "." + member.name : member.name, member);
  }
  return m;
}

// ── usage scan (repo -> Bun.* tokens) ───────────────────────────────────────

const TOKEN_RE = /Bun\.[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)?/g;
// src/tools/scripts only — test fixtures would pollute the manifest.
const SCAN_DIRS = ["src", "tools", "scripts"];

/** rg scan of the repo source dirs -> token -> count. Offline. */
export function scanBunTokens(root: string): Map<string, number> {
  const counts = new Map<string, number>();
  const proc = Bun.spawnSync([
    "rg", "-o", "Bun\\.[A-Za-z_$][A-Za-z0-9_$]*(?:\\.[A-Za-z_$][A-Za-z0-9_$]*)?",
    ...SCAN_DIRS, "--no-filename", "-g", "!*.json",
  ], { cwd: root, stdout: "pipe", stderr: "pipe" });
  const out = proc.stdout.toString();
  if (out.length === 0) return counts;
  for (const match of out.match(/\S+/g) ?? []) {
    counts.set(match, (counts.get(match) ?? 0) + 1);
  }
  return counts;
}

/**
 * Resolve a repo token ("Bun.XML.parse", "Bun.file") against the shape:
 * longest ns.name match, else top-level name, else null.
 */
export function resolveToken(token: string, lookup: Map<string, ShapeMember>): ShapeMember | null {
  const parts = token.split("."); // ["Bun", "XML", "parse"]
  const dotted = parts.slice(1).join(".");
  if (lookup.has(dotted)) return lookup.get(dotted)!;
  const top = parts[1] ?? "";
  return lookup.get(top) ?? null;
}

// ── canonical docs URLs (validated live against bun.com, 1.4.0 docs) ────────

/**
 * Top-level shape member name -> canonical guide URL. Every value was
 * HTTP-verified (200) during the P0 build; `ground:check --online` re-verifies.
 * Sub-namespace members inherit their namespace's URL.
 */
export const DOCS_URL: Record<string, string> = {
  file: "https://bun.com/docs/runtime/file-io#reading-files-bun-file",
  write: "https://bun.com/docs/runtime/file-io#writing-files-bun-write",
  stdout: "https://bun.com/docs/runtime/file-io",
  stdin: "https://bun.com/docs/runtime/file-io",
  stderr: "https://bun.com/docs/runtime/file-io",
  mmap: "https://bun.com/docs/runtime/file-io",
  Archive: "https://bun.com/docs/runtime/archive",
  "$": "https://bun.com/docs/runtime/shell",
  semver: "https://bun.com/docs/runtime/utils",
  JSON5: "https://bun.com/docs/runtime/json5",
  sha: "https://bun.com/docs/runtime/utils",
  spawn: "https://bun.com/docs/runtime/child-process",
  spawnSync: "https://bun.com/docs/runtime/child-process",
  build: "https://bun.com/docs/bundler",
  plugin: "https://bun.com/docs/bundler/plugins",
  serve: "https://bun.com/docs/runtime/http/server",
  fetch: "https://bun.com/docs/runtime/networking/fetch",
  sql: "https://bun.com/docs/runtime/sql",
  SQL: "https://bun.com/docs/runtime/sql",
  cron: "https://bun.com/docs/runtime/cron",
  color: "https://bun.com/docs/runtime/color",
  inspect: "https://bun.com/docs/runtime/utils",
  escapeHTML: "https://bun.com/docs/runtime/utils",
  stringWidth: "https://bun.com/docs/runtime/utils",
  stripANSI: "https://bun.com/docs/runtime/utils",
  sliceAnsi: "https://bun.com/docs/runtime/utils",
  wrapAnsi: "https://bun.com/docs/runtime/utils",
  peek: "https://bun.com/docs/runtime/utils",
  sleep: "https://bun.com/docs/runtime/utils#bun-sleep",
  sleepSync: "https://bun.com/docs/runtime/utils",
  version: "https://bun.com/docs/runtime/utils",
  revision: "https://bun.com/docs/runtime/utils",
  nanoseconds: "https://bun.com/docs/runtime/utils",
  env: "https://bun.com/docs/runtime/environment-variables",
  argv: "https://bun.com/docs/runtime/utils",
  ArrayBufferSink: "https://bun.com/docs/runtime/utils",
  Transpiler: "https://bun.com/docs/runtime/utils",
  Terminal: "https://bun.com/docs/runtime/utils",
  WebView: "https://bun.com/docs/runtime/webview",
  readableStreamToArrayBuffer: "https://bun.com/docs/runtime/utils",
  readableStreamToText: "https://bun.com/docs/runtime/utils",
  readableStreamToFormData: "https://bun.com/docs/runtime/utils",
  readableStreamToArray: "https://bun.com/docs/runtime/utils",
  readableStreamToBlob: "https://bun.com/docs/runtime/utils",
  readableStreamToBytes: "https://bun.com/docs/runtime/utils",
  readableStreamToJSON: "https://bun.com/docs/runtime/utils",
  CryptoHasher: "https://bun.com/docs/runtime/utils",
  SHA256: "https://bun.com/docs/runtime/utils",
  SHA512_256: "https://bun.com/docs/runtime/utils",
  hash: "https://bun.com/docs/runtime/utils",
  deepEquals: "https://bun.com/docs/runtime/utils",
  randomUUIDv7: "https://bun.com/docs/runtime/utils",
  randomUUIDv5: "https://bun.com/docs/runtime/utils",
  password: "https://bun.com/docs/runtime/utils",
  Image: "https://bun.com/docs/runtime/image",
  markdown: "https://bun.com/docs/runtime/markdown",
  XML: "https://bun.com/docs/runtime/xml",
  TOML: "https://bun.com/docs/runtime/toml",
  JSONL: "https://bun.com/docs/runtime/jsonl",
  YAML: "https://bun.com/docs/runtime/yaml",
  JSONC: "https://bun.com/docs/runtime/json5",
  Glob: "https://bun.com/docs/runtime/glob",
  which: "https://bun.com/docs/runtime/utils",
  resolve: "https://bun.com/docs/runtime/utils",
  fileURLToPath: "https://bun.com/docs/runtime/utils",
  pathToFileURL: "https://bun.com/docs/runtime/utils",
  openInEditor: "https://bun.com/docs/runtime/utils",
  connect: "https://bun.com/docs/runtime/networking/tcp",
  listen: "https://bun.com/docs/runtime/networking/tcp",
  udpSocket: "https://bun.com/docs/runtime/networking/udp",
  dns: "https://bun.com/docs/runtime/networking/dns",
  redis: "https://bun.com/docs/runtime/redis",
  secrets: "https://bun.com/docs/runtime/secrets",
  CSRF: "https://bun.com/docs/runtime/csrf",
  Cookie: "https://bun.com/docs/runtime/cookies",
  CookieMap: "https://bun.com/docs/runtime/cookies",
  s3: "https://bun.com/docs/runtime/s3",
  S3Client: "https://bun.com/docs/runtime/s3",
  postgres: "https://bun.com/docs/runtime/sql",
  RedisClient: "https://bun.com/docs/runtime/redis",
  gc: "https://bun.com/docs/runtime/utils",
  shrink: "https://bun.com/docs/runtime/utils",
  generateHeapSnapshot: "https://bun.com/docs/runtime/utils",
  isMainThread: "https://bun.com/docs/runtime/utils",
  isStandaloneExecutable: "https://bun.com/docs/runtime/utils",
  main: "https://bun.com/docs/runtime/utils",
  unsafe: "https://bun.com/docs/runtime/utils",
  indexOfLine: "https://bun.com/docs/runtime/utils",
  resolveSync: "https://bun.com/docs/runtime/utils",
  allocUnsafe: "https://bun.com/docs/runtime/utils",
  embeddedFiles: "https://bun.com/docs/runtime/utils",
  enableANSIColors: "https://bun.com/docs/runtime/utils",
  FFI: "https://bun.com/docs/runtime/ffi",
  BuildArtifact: "https://bun.com/docs/bundler",
  BuildConfig: "https://bun.com/docs/bundler",
  FileSystemRouter: "https://bun.com/docs/runtime/file-system-router",
  deepMatch: "https://bun.com/docs/runtime/utils",
  concatArrayBuffers: "https://bun.com/docs/runtime/utils",
};

export function docsUrlFor(member: ShapeMember): string {
  const url = DOCS_URL[member.name] ?? (member.ns ? DOCS_URL[member.ns] : undefined);
  return url ?? "https://bun.com/docs/runtime";
}

// ── stale-URL detection (the /docs/api/* scheme is dead; blocklist is 404s) ──

export const STALE_URL_PATTERNS: RegExp[] = [
  /bun\.com\/docs\/api\//, // whole /docs/api/* tree redirects/404s
  /bun\.com\/docs\/runtime\/api\b/, // 404
  /bun\.com\/docs\/runtime\/bun-write\b/, // 404 (guide moved into file-io)
  /bun\.com\/docs\/runtime\/bun-secrets\b/, // 404 (page is /docs/runtime/secrets)
  /bun\.com\/docs\/runtime\/websockets\b/, // 404 (page is /docs/runtime/http/websockets)
  /bun\.com\/docs\/runtime\/postgres\b/, // 404 (page is /docs/runtime/sql)
  /bun\.com\/docs\/runtime\/terminal\b/, // 404 (Terminal lives in utils/reference)
];

/** Scan a blob of text for stale bun.com doc URLs. */
export function findStaleUrls(text: string): string[] {
  const found: string[] = [];
  for (const re of STALE_URL_PATTERNS) {
    const m = text.match(re);
    if (m) found.push(m[0]);
  }
  return [...new Set(found)];
}

// ── manifest schema ──────────────────────────────────────────────────────────

export interface GroundRow {
  symbol: string;
  name: string;
  ns: string;
  kind: string;
  typeOnly: boolean;
  /** typeof Bun.<top> !== "undefined" on the installed runtime (offline check). */
  runtime: boolean;
  used: boolean;
  usageCount: number;
  docsUrl: string;
  gate: string;
  probeWired: boolean;
}

export interface GroundManifest {
  bunVersion: string;
  shapeRevision: string;
  generatedAt: string;
  generator: string;
  shapeFile: string;
  docsIndex: string;
  rows: GroundRow[];
  unknownTokens: string[];
  staleUrlCount: number;
}

/** Normalize a gateFor() result: strip " (ns)", map GAP to "". */
export function normalizeGate(raw: string): string {
  const g = raw.replace(/\s+\(ns\)$/, "");
  return g === "GAP" || g === "undefined" ? "" : g;
}

/**
 * Known false-positive tokens (types, module namespaces, CLI flags and
 * metasyntactic examples in comments/docs) — filtered out of the manifest's
 * unknownTokens list so real drift stays visible.
 */
export const UNKNOWN_TOKEN_ALLOWLIST: ReadonlySet<string> = new Set([
  "Bun.File", "Bun.Args", "Bun.CSV", "Bun.Request", "Bun.SourceMap", "Bun.Shell", // type-only / doc names
  "Bun.Foo", "Bun.X", "Bun.S", "Bun.x", "Bun.term", "Bun.tok", // metasyntactic / truncated
  "Bun.ffi", "Bun.Networking", "Bun.Quic", // module namespaces (bun:ffi), not Bun.* members
  "Bun.gzip", "Bun.zstd", "Bun.rename", "Bun.watch", "Bun.map", "Bun.html", // CLI flags / prose
  "Bun.image", "Bun.isTerminal", "Bun.fullName", "Bun.dimension", "Bun.readableStreamTo", // prose / partial names
]);
