/**
 * maps-lock.ts — the maps.toml triple-lock.
 *
 * Three surfaces must agree for the Bun docs pipeline to be trustworthy:
 *   maps.toml (committed lock manifest) + bun-types/@types/bun pins
 *   (package.json) + Bun.version (runtime) + the true docs index
 *   (bun.com/llm.txt, fingerprinted as "llm#" + llmHash in
 *   research/cache/bun-docs/DISCOVERY.json and INDEX.json). When Bun bumps
 *   or llm.txt changes, docs:refresh detects the drift via the mapsHash,
 *   re-indexes from llm.txt, regenerates maps.toml, and records the new
 *   hash in INDEX.json — self-healing instead of silently stale.
 *
 * Hash: Bun.hash(canonical pins content).toString(16) — the repo's
 * fingerprint pattern (src/research/bun-native.ts), 16 hex chars.
 *
 * Purity: everything below evaluateMapsLock is a pure function (no
 * network, no subprocess) and unit-tested in tests/lib/maps-lock.test.ts.
 * syncDocsLock() is the orchestration used by tools/bun-docs-refresh-cli.ts
 * and tools/bun-docs-refresh-scheduled.ts.
 */
import { join } from "node:path";
import { runBunCommand } from "./run-bun.ts";

export const ROOT = join(import.meta.dir, "..", "..");
export const MAPS_TOML_PATH = join(ROOT, "maps.toml");
export const BUN_DOCS_INDEX_PATH = join(ROOT, "research/cache/bun-docs/INDEX.json");
export const BUN_DOCS_DISCOVERY_PATH = join(ROOT, "research/cache/bun-docs/DISCOVERY.json");

export type MapsPins = {
  /** Runtime: Bun.version */
  bunVersion: string;
  /** package.json devDependencies.bun-types */
  bunTypesVersion: string;
  /** package.json devDependencies["@types/bun"] */
  typesBunVersion: string;
  /** Docs index fingerprint: "llm#" + Bun.hash(bun.com/llm.txt).toString(16) */
  docsRef: string;
  /** Indexed page count */
  docsPages: number;
};

export type MapsLockEval = {
  ok: boolean;
  reasons: string[];
  /** Hash of maps.toml pins on disk (null when the file is missing). */
  fileHash: string | null;
  /** INDEX.json mapsHash (null when absent). */
  recordedHash: string | null;
  /** Hash of the expected pins. */
  expectedHash: string;
  expected: MapsPins;
  filePins: MapsPins | null;
};

export type SyncDocsLockResult = {
  ok: boolean;
  lockOk: boolean;
  regenerated: boolean;
  reasons: string[];
  hash: string;
  pages: number;
  bunVersion: string;
};

const PIN_KEYS: ReadonlyArray<keyof MapsPins> = [
  "bunVersion",
  "bunTypesVersion",
  "typesBunVersion",
  "docsRef",
  "docsPages",
];

/** Canonical, stable pins content — the hash input (no timestamps). */
export function mapsPinsContent(p: MapsPins): string {
  return [
    `runtime.bun = "${p.bunVersion}"`,
    `types.bun-types = "${p.bunTypesVersion}"`,
    `types."@types/bun" = "${p.typesBunVersion}"`,
    `docs.ref = "${p.docsRef}"`,
    `docs.pages = ${p.docsPages}`,
    "",
  ].join("\n");
}

/** 64-bit Bun.hash of the pins, as 16 zero-padded hex chars. */
export function mapsHashOfPins(p: MapsPins): string {
  return Bun.hash(mapsPinsContent(p)).toString(16).padStart(16, '0');
}

/** The committed maps.toml body (generated line is metadata, not hashed). */
export function mapsTomlContent(p: MapsPins, generatedAt: string): string {
  return [
    "# maps.toml — triple-lock manifest: Bun.version + bun-types + docs index.",
    "# Generated by `bun run docs:refresh` (tools/bun-docs-refresh-cli.ts /",
    "# tools/bun-docs-refresh-scheduled.ts). Do not edit by hand.",
    "# docs.ref = llm.txt index fingerprint (llm#<Bun.hash of bun.com/llm.txt>).",
    '# INDEX.json records the pins hash as "mapsHash" (Bun.hash hex).',
    "",
    `generated = "${generatedAt}"`,
    "",
    "[runtime]",
    `bun = "${p.bunVersion}"`,
    "",
    "[types]",
    `bun-types = "${p.bunTypesVersion}"`,
    `"@types/bun" = "${p.typesBunVersion}"`,
    "",
    "[docs]",
    `ref = "${p.docsRef}"`,
    `pages = ${p.docsPages}`,
    "",
  ].join("\n");
}

/** Extract pins from a Bun.TOML.parse result; null on any missing field. */
export function parseMapsPins(parsed: unknown): MapsPins | null {
  if (!parsed || typeof parsed !== "object") return null;
  const runtime = (parsed as Record<string, any>).runtime as Record<string, any> | undefined;
  const types = (parsed as Record<string, any>).types as Record<string, any> | undefined;
  const docs = (parsed as Record<string, any>).docs as Record<string, any> | undefined;
  if (!runtime || !types || !docs) return null;
  const bunVersion = typeof runtime.bun === "string" ? runtime.bun : null;
  const bunTypesVersion = typeof types["bun-types"] === "string" ? types["bun-types"] : null;
  const typesBunVersion = typeof types["@types/bun"] === "string" ? types["@types/bun"] : null;
  const docsRef = typeof docs.ref === "string" ? docs.ref : null;
  const docsPages = typeof docs.pages === "number" ? docs.pages : null;
  if (bunVersion === null || bunTypesVersion === null || typesBunVersion === null || docsRef === null || docsPages === null) {
    return null;
  }
  return { bunVersion, bunTypesVersion, typesBunVersion, docsRef, docsPages };
}

/** Read + parse the committed maps.toml; null when absent or malformed. */
export async function readMapsToml(): Promise<MapsPins | null> {
  try {
    const text = await Bun.file(MAPS_TOML_PATH).text();
    return parseMapsPins(Bun.TOML.parse(text));
  } catch {
    return null;
  }
}

/**
 * Evaluate the triple-lock: maps.toml pins, INDEX.json mapsHash, and the
 * expected pins (runtime + package.json + indexed surface) must all agree.
 * Pure — no I/O beyond what the caller passes in.
 */
export function evaluateMapsLock(input: {
  expectedPins: MapsPins;
  filePins: MapsPins | null;
  recordedHash: string | null;
}): MapsLockEval {
  const { expectedPins, filePins, recordedHash } = input;
  const reasons: string[] = [];
  const expectedHash = mapsHashOfPins(expectedPins);

  let fileHash: string | null = null;
  if (filePins) {
    fileHash = mapsHashOfPins(filePins);
    if (fileHash !== expectedHash) {
      reasons.push(`maps.toml pins stale: file ${fileHash} != expected ${expectedHash}`);
      for (const k of PIN_KEYS) {
        const fv = filePins[k];
        const ev = expectedPins[k];
        if (fv !== ev) reasons.push(`  ${k}: ${String(fv)} -> ${String(ev)}`);
      }
    }
  } else {
    reasons.push("maps.toml missing");
  }

  if (recordedHash === null) {
    reasons.push("INDEX.json mapsHash missing");
  } else if (recordedHash !== expectedHash) {
    reasons.push(`INDEX.json mapsHash ${recordedHash} != expected ${expectedHash}`);
  }

  if (fileHash !== null && recordedHash !== null && fileHash !== recordedHash) {
    reasons.push(`INDEX.json mapsHash ${recordedHash} != maps.toml pins hash ${fileHash}`);
  }

  return {
    ok: reasons.length === 0,
    reasons,
    fileHash,
    recordedHash,
    expectedHash,
    expected: expectedPins,
    filePins,
  };
}

function loadIndex(): Promise<any | null> {
  return Bun.file(BUN_DOCS_INDEX_PATH).text()
    .then((t) => JSON.parse(t) as any)
    .catch(() => null);
}

async function saveIndex(idx: any): Promise<void> {
  await Bun.write(BUN_DOCS_INDEX_PATH, JSON.stringify(idx, null, 2) + "\n");
}

/**
 * The docs:refresh pipeline: index (or gate) the docs cache, evaluate the
 * maps triple-lock, and self-heal on mismatch — re-index from bun.com/llm.txt,
 * regenerate maps.toml from the indexed surface, record the new mapsHash in
 * INDEX.json. check-only mode (skipNetwork) never writes:
 * a mismatch is reported and the caller decides (exit 1 / cron failure).
 */
export async function syncDocsLock(opts: { skipNetwork: boolean }): Promise<SyncDocsLockResult> {
  const run = (args: string[]) => runBunCommand(args, { cwd: ROOT });
  const now = new Date().toISOString();

  // 1) Index the docs cache (or offline-gate it in check-only mode).
  if (!opts.skipNetwork) {
    const r = await run(["run", "bun:docs-index"]);
    if (!r.ok) throw new Error("docs index refresh failed: " + r.lastLine);
    // 1b) Per-scope discovery lists (DISCOVERY.json scopes.*) — the
    // bun-docs cache tests read the bundler scope. Best-effort: the lock
    // contract (scope "all") stays the only hard gate.
    await run(["run", "bun:docs-index", "--scope", "bundler"]);
  } else {
    const c = await run(["run", "bun:docs-index", "--check"]);
    if (!c.ok) throw new Error("docs index gate failed: " + c.lastLine);
  }

  // 2) Expected pins from reality: runtime, package.json, indexed surface.
  // docsRef = "llm#" + Bun.hash(bun.com/llm.txt) from DISCOVERY.json — the
  // indexer wrote it (network mode) or it is cached from the last run
  // (offline check mode); "llm#missing" drifts the lock, self-healing
  // re-indexes from the fresh map.
  const pkg = (await Bun.file(join(ROOT, "package.json")).json().catch(() => null)) as any;
  const bunTypes = pkg?.devDependencies?.["bun-types"] ?? pkg?.dependencies?.["bun-types"] ?? "unknown";
  const typesBun = pkg?.devDependencies?.["@types/bun"] ?? pkg?.dependencies?.["@types/bun"] ?? "unknown";
  const idx = await loadIndex();
  const discovery = (await Bun.file(BUN_DOCS_DISCOVERY_PATH).json().catch(() => null)) as { source?: string; llmHash?: string } | null;
  const llmHash = discovery?.source === "llm" && typeof discovery.llmHash === "string" ? discovery.llmHash : "missing";
  const expected: MapsPins = {
    bunVersion: Bun.version,
    bunTypesVersion: String(bunTypes),
    typesBunVersion: String(typesBun),
    docsRef: "llm#" + llmHash,
    docsPages: Array.isArray(idx?.pages) ? idx.pages.length : 0,
  };

  // 3) Evaluate the lock.
  const filePins = await readMapsToml();
  const recordedHash = idx?.mapsHash ?? null;
  const state = evaluateMapsLock({ expectedPins: expected, filePins, recordedHash });

  // 4) Mismatch: log, then self-heal (network mode only).
  if (!state.ok) {
    console.error("[maps-lock] MISMATCH (" + state.reasons.length + "):");
    for (const reason of state.reasons) console.error("  - " + reason);
    if (opts.skipNetwork) {
      return {
        ok: false,
        lockOk: false,
        regenerated: false,
        reasons: state.reasons,
        hash: state.expectedHash,
        pages: expected.docsPages,
        bunVersion: expected.bunVersion,
      };
    }
    // Re-index once more (the indexer re-reads llm.txt, so a Bun bump or a
    // docs-map change forces re-discovery), then regenerate.
    const r2 = await run(["run", "bun:docs-index"]);
    if (!r2.ok) throw new Error("docs index re-run after lock mismatch failed: " + r2.lastLine);
    const idx2 = await loadIndex();
    if (Array.isArray(idx2?.pages)) expected.docsPages = idx2.pages.length;
    const disc2 = (await Bun.file(BUN_DOCS_DISCOVERY_PATH).json().catch(() => null)) as { source?: string; llmHash?: string } | null;
    if (disc2?.source === "llm" && typeof disc2.llmHash === "string") expected.docsRef = "llm#" + disc2.llmHash;

    const newHash = mapsHashOfPins(expected);
    await Bun.write(MAPS_TOML_PATH, mapsTomlContent(expected, now));
    const idx3 = (await loadIndex()) ?? { pages: [] };
    idx3.mapsHash = newHash;
    idx3.mapsMeta = {
      bunVersion: expected.bunVersion,
      bunTypes: expected.bunTypesVersion,
      typesBun: expected.typesBunVersion,
      source: "llm",
      ref: expected.docsRef,
      pages: expected.docsPages,
      checkedAt: now,
      lastMismatchAt: now,
      previousHash: state.recordedHash,
    };
    await saveIndex(idx3);
    console.error(`[maps-lock] regenerated maps.toml + INDEX.json mapsHash=${newHash}`);
    return {
      ok: true,
      lockOk: false,
      regenerated: true,
      reasons: state.reasons,
      hash: newHash,
      pages: expected.docsPages,
      bunVersion: expected.bunVersion,
    };
  }

  // 5) In sync: refresh metadata only.
  const idx4 = (await loadIndex()) ?? { pages: [] };
  idx4.mapsHash = state.expectedHash;
  idx4.mapsMeta = {
    ...(idx4.mapsMeta ?? {}),
    bunVersion: expected.bunVersion,
    bunTypes: expected.bunTypesVersion,
    typesBun: expected.typesBunVersion,
    source: "llm",
    ref: expected.docsRef,
    pages: expected.docsPages,
    checkedAt: now,
  };
  await saveIndex(idx4);
  console.log(`[maps-lock] ok ${state.expectedHash} (${expected.docsPages} pages)`);
  return {
    ok: true,
    lockOk: true,
    regenerated: false,
    reasons: [],
    hash: state.expectedHash,
    pages: expected.docsPages,
    bunVersion: expected.bunVersion,
  };
}
