export {
  SPORTS,
  SPORT_CATEGORIES,
  getSport,
  getSportsByCategory,
  isSportId,
  listSports,
  type SportCategory,
  type SportId,
  type SportRecord,
} from './sports.ts';

export {
  LIVE_PRODUCT_IDS,
  LIVE_PRODUCTS,
  LEGACY_CAPACITY_LIVE_PRODUCTS,
  getLiveProduct,
  isLiveProductId,
  isLegacyCapacityLiveProduct,
  listLiveProducts,
  liveProductOwnsCoverage,
  normalizeLiveProductName,
  type LegacyCapacityLiveProduct,
  type LiveProductId,
  type LiveProductRecord,
} from './live-products.ts';

export {
  PLIVE_STREAM_ENDPOINTS,
  STATSCORE_BOOKED_EVENTS,
  ULTRA_DESK_API_PATHS,
  defaultLiveWidgetUrl,
  defaultUltraStreamEndpoints,
  listLiveProductInfraApexHosts,
  streamEndpointsForLiveProduct,
  type LiveStreamEndpoints,
} from './live-product-endpoints.ts';

export {
  FINGERPRINT_PENDING_SKINS,
  assertFingerprintCoverage,
  buildSkinMatrixRows,
  formatSkinMatrixMarkdownTable,
  formatSkinMatrixText,
  gapsForSkin,
  type SkinMatrixGap,
  type SkinMatrixRow,
} from './skin-matrix.ts';

export {
  CATEGORY_CAPS,
  buildHostObservations,
  decisionForScore,
  scoreFromEvidence,
  scoreHostAgainstSkins,
  scoreSkinObservations,
  type EvidenceCategory,
  type HostDiscoverDecision,
  type HostObservations,
  type SkinWeightedScore,
  type WeightedEvidenceItem,
} from './host-weighted-score.ts';

export {
  DEFAULT_HOST_DISCOVER_ARTIFACT_DIR,
  HOST_DISCOVER_BASELINES,
  HOST_FINGERPRINT_RULES,
  adapterIdForMappedSkin,
  collectHtmlUrls,
  discoverHost,
  extractAbsoluteUrls,
  extractUrlsFromHar,
  formatHostDiscoverText,
  listMappedDiscoverHosts,
  listPublicFingerprintRules,
  listSkinBrandFingerprintRules,
  persistHostDiscoverUrls,
  scoreHostDiscovery,
  type DeskAdapterId,
  type HostDiscoverEvidence,
  type HostDiscoverReport,
  type HostDiscoverTarget,
  type HostDiscoverWeigh,
  type SuggestedSkinId,
} from './host-discover.ts';

export {
  HOST_TO_SKIN,
  SKIN_IDS,
  SKINS,
  apexHost,
  defaultUrlForMapperKind,
  defaultUrlForSkin,
  defaultUrlForUltraMapper,
  getSkin,
  getSkinByHost,
  isSkinId,
  listSkinApexHosts,
  listSkins,
  normalizeHost,
  DESK_DOMAIN_ENV,
  RETIRED_BARE_BOOK_DOMAIN_ENVS,
  isRetiredBareBookDomainEnv,
  assertActiveSkinsHaveHosts,
  listActiveSkins,
  requireDefaultUrlForUltraMapper,
  deskDomainFromEnvMap,
  resolveDeskDomainFromEnv,
  resolveSkinId,
  skinOfferedCatalogNames,
  skinOffersLiveProduct,
  urlForHost,
  type SkinFingerprints,
  type SkinId,
  type SkinMapper,
  type SkinRecord,
} from './skins.ts';

export {
  BINDING_STATUSES,
  LIVE_PRODUCT_SPORT_BINDINGS,
  listLiveProductSportBindings,
  liveProductHasSportCoverage,
  liveProductsWithBindings,
  type BindingStatus,
  type LiveProductSportBinding,
} from './live-product-sport-bindings.ts';

export {
  FEED_SPORT,
  PANDORA_FEED_SPORTS,
  feedSportIdsForSport,
  feedSportName,
  feedSportSlug,
  getPandoraFeedSport,
  listMappedFeedSports,
  listPandoraFeedSports,
  sportIdFromFeedSportId,
  type PandoraFeedSport,
  type PandoraFeedSportKind,
} from './pandora-feed-sports.ts';

export {
  DEFAULT_COVERAGE_LIVE_PRODUCT,
  WIDGET_FAVORITES_SPORT_ID,
  resolveSport,
  type ResolveSportQuery,
  type ResolvedSport,
} from './resolve-sport.ts';

export {
  COMPETITIONS,
  COMPETITION_GENDERS,
  competitionSlugFromLeague,
  getCompetition,
  inferGenderFromLeagueLabel,
  isCompetitionId,
  listCompetitions,
  listCompetitionsBySport,
  matchLeagueKey,
  normalizeLeagueKey,
  type CompetitionGender,
  type CompetitionId,
  type CompetitionRecord,
  type PliveCompetitionMapping,
} from './competitions.ts';

export {
  resolveCompetition,
  type ResolveCompetitionQuery,
  type ResolvedCompetition,
} from './resolve-competition.ts';

export {
  applyCompetitionRecordsToSource,
  competitionRecordFromLeague,
  formatCompetitionRecordSource,
  hasLeagueStructureMarker,
  isPromotableLeagueLabel,
  junkLeagueReason,
  mintCompetitionId,
  planCompetitionPromote,
  type CompetitionPromoteCandidate,
  type CompetitionPromotePlan,
  type CompetitionPromoteRejection,
  type JunkLeagueReason,
  type PromoteLeagueInput,
} from './competition-promote.ts';

export {
  applyPandoraPromoteToCompetitionsFile,
  buildPandoraCoverageReport,
  buildPandoraSportMap,
  formatPandoraCoverageReport,
  formatPandoraPromotePlan,
  liveLeaguesToPromoteInputs,
  loadWidgetDomainSnapshot,
  planPandoraCompetitionPromote,
  type PandoraCoverageReport,
  type PandoraPromoteResult,
  type PandoraSportMapEntry,
} from './pandora-domain-integrate.ts';

export {
  buildDomainGaps,
  defaultWidgetDomainCachePath,
  extractLanguageTexts,
  extractMarketLabelsFromTexts,
  extractShellSportsFromScript,
  extractWidgetDomain,
  formatWidgetDomainSnapshot,
  mapLiveSportNameToSportId,
  resolveLeagueFeedSportId,
  resolveLiveSportId,
  parseLiveLeaguesRoom,
  parseLiveSportsRoom,
  parseSportPeriodRoom,
  parseWagerTypesRoom,
  sportPeriodLabel,
  wagerTypeFamilyCounts,
  writeWidgetDomainSnapshot,
  type DomainGapReport,
  type SportPeriodLanguageBlock,
  type WidgetDomainSnapshot,
  type WidgetLiveLeague,
  type WidgetLiveSport,
  type WidgetMarketLabel,
  type WidgetShellSport,
  type WidgetSportPeriods,
  type WidgetWagerType,
} from './widget-domain-extract.ts';

export {
  EXAMPLE_DARIN_PLACHY_ODDS_LINE,
  EXAMPLE_DARIN_PLACHY_TICKET_LEG,
  KNOWN_MARKET_LABELS,
  PANDORA_PERIOD_CODES,
  PSEUDO_PERIOD_TO_MATCH,
  canonicalizePeriodId,
  describeOddsLine,
  describeTicketLeg,
  isPandoraPeriodCode,
  marketLabel,
  oddsLineFromCoefficient,
  oddsLineFromTicketLeg,
  periodLabel,
  ticketLegFromOddsLine,
  ticketLegFromWire,
  type CoefficientLineCoords,
  type InventoryEventRef,
  type KnownMarketId,
  type OddsEventRef,
  type OddsLine,
  type PandoraPeriodCode,
  type TicketLeg,
  type TicketLegCoords,
} from './odds-selection.ts';

export {
  BOOKS,
  BOOK_IDS,
  HOST_TO_BOOK,
  bookOffersLiveProduct,
  buildBookMatrixRows,
  formatBooksMatrixText,
  getBook,
  getBookByHost,
  isBookId,
  listBookIdsForSkin,
  listBooks,
  listBooksForSkin,
  resolveBookId,
  skinIdForBook,
  type BookId,
  type BookMatrixRow,
  type BookRecord,
} from './books.ts';
