export {
  SPORTS,
  SPORT_CATEGORIES,
  getSport,
  getSportsByCategory,
  isSportId,
  listSports,
  type SportCategory,
  type SportId,
  type SportRecord,
} from './sports.ts';

export {
  LIVE_PRODUCT_IDS,
  LIVE_PRODUCTS,
  LEGACY_CAPACITY_LIVE_PRODUCTS,
  getLiveProduct,
  isLiveProductId,
  isLegacyCapacityLiveProduct,
  listLiveProducts,
  liveProductOwnsCoverage,
  normalizeLiveProductName,
  type LegacyCapacityLiveProduct,
  type LiveProductId,
  type LiveProductRecord,
} from './live-products.ts';

export {
  PLIVE_STREAM_ENDPOINTS,
  STATSCORE_BOOKED_EVENTS,
  ULTRA_DESK_API_PATHS,
  defaultLiveWidgetUrl,
  defaultUltraStreamEndpoints,
  listLiveProductInfraApexHosts,
  streamEndpointsForLiveProduct,
  type LiveStreamEndpoints,
} from './live-product-endpoints.ts';

export {
  FINGERPRINT_PENDING_SKINS,
  assertFingerprintCoverage,
  buildSkinMatrixRows,
  formatSkinMatrixMarkdownTable,
  formatSkinMatrixText,
  gapsForSkin,
  type SkinMatrixGap,
  type SkinMatrixRow,
} from './skin-matrix.ts';

export {
  HOST_TO_SKIN,
  SKIN_IDS,
  SKINS,
  apexHost,
  defaultUrlForMapperKind,
  defaultUrlForSkin,
  defaultUrlForUltraMapper,
  getSkin,
  getSkinByHost,
  isSkinId,
  listSkinApexHosts,
  listSkins,
  normalizeHost,
  normalizeSkinName,
  DESK_DOMAIN_ENV,
  PARTNER_DOMAIN_ENV,
  RETIRED_BARE_BOOK_DOMAIN_ENVS,
  isRetiredBareBookDomainEnv,
  assertActiveSkinsHaveHosts,
  listActiveSkins,
  requireDefaultUrlForUltraMapper,
  deskDomainFromEnvMap,
  resolveDeskDomainFromEnv,
  resolveSkinId,
  skinOfferedCatalogNames,
  skinOffersLiveProduct,
  urlForHost,
  type SkinFingerprints,
  type SkinId,
  type SkinMapper,
  type SkinRecord,
} from './skins.ts';

export {
  BINDING_STATUSES,
  LIVE_PRODUCT_SPORT_BINDINGS,
  SKIN_SPORT_BINDINGS,
  listLiveProductSportBindings,
  listSkinSportBindings,
  liveProductHasSportCoverage,
  liveProductsWithBindings,
  skinHasSportCoverage,
  skinsWithBindings,
  type BindingStatus,
  type LiveProductSportBinding,
  type SkinSportBinding,
} from './live-product-sport-bindings.ts';

export {
  DEFAULT_COVERAGE_LIVE_PRODUCT,
  DEFAULT_COVERAGE_SKIN,
  WIDGET_FAVORITES_SPORT_ID,
  resolveSport,
  type ResolveSportQuery,
  type ResolvedSport,
} from './resolve-sport.ts';

export {
  COMPETITIONS,
  COMPETITION_GENDERS,
  competitionSlugFromLeague,
  getCompetition,
  inferGenderFromLeagueLabel,
  isCompetitionId,
  listCompetitions,
  listCompetitionsBySport,
  normalizeLeagueKey,
  type CompetitionGender,
  type CompetitionId,
  type CompetitionRecord,
  type PliveCompetitionMapping,
} from './competitions.ts';

export {
  resolveCompetition,
  type ResolveCompetitionQuery,
  type ResolvedCompetition,
} from './resolve-competition.ts';

export {
  EXAMPLE_DARIN_PLACHY_ODDS_LINE,
  EXAMPLE_DARIN_PLACHY_TICKET_LEG,
  KNOWN_MARKET_LABELS,
  describeOddsLine,
  describeTicketLeg,
  marketLabel,
  oddsLineFromCoefficient,
  oddsLineFromTicketLeg,
  periodLabel,
  ticketLegFromOddsLine,
  ticketLegFromWire,
  type CoefficientLineCoords,
  type InventoryEventRef,
  type KnownMarketId,
  type OddsEventRef,
  type OddsLine,
  type TicketLeg,
  type TicketLegCoords,
} from './odds-selection.ts';

export {
  BOOKS,
  BOOK_IDS,
  HOST_TO_BOOK,
  bookOffersLiveProduct,
  bookOffersSkin,
  buildBookMatrixRows,
  formatBooksMatrixText,
  getBook,
  getBookByHost,
  isBookId,
  listBookIdsForSkin,
  listBooks,
  listBooksForSkin,
  resolveBookId,
  skinIdForBook,
  type BookId,
  type BookMatrixRow,
  type BookRecord,
} from './books.ts';
