/**
 * Baked Pandora live.sportPeriod (English) — period labels by feedSportId.
 *
 * Captured 2026-08-10. Regenerate via tools/bake-sport-periods.ts from a capture.
 *
 * Segment codes are often s1…s10 even when the unit is Inning/Quarter/Game/Set.
 * Prefer periodLabelForFeedSport(feedSportId, code) over generic periodLabel.
 */

export type PandoraSportPeriodBake = {
  capturedAt: string;
  language: string;
  /** feedSportId → unit noun (Inning, Quarter, Set, Game, …) */
  periodUnit: Readonly<Record<string, string>>;
  /** feedSportId → periodCode → display label */
  periods: Readonly<Record<string, Readonly<Record<string, string>>>>;
  abbreviations: Readonly<Record<string, string>>;
};

export const PANDORA_SPORT_PERIODS: PandoraSportPeriodBake = {
  "capturedAt": "2026-08-10",
  "language": "en",
  "periodUnit": {
    "1": "Inning",
    "2": "Quarter",
    "3": "Quarter",
    "4": "Period",
    "5": "Half",
    "6": "Round",
    "7": "Round",
    "8": "Set",
    "13": "Round",
    "27": "Round",
    "86": "Half",
    "87": "Inns",
    "88": "Set",
    "92": "Half",
    "93": "Game",
    "94": "Quarter",
    "95": "Game",
    "98": "Frame",
    "99": "Quarter",
    "102": "Half",
    "103": "Half",
    "104": "Half",
    "110": "Set",
    "114": "Map",
    "120": "Period",
    "121": "Game",
    "163": "Half",
    "173": "Frame",
    "190": "Inning",
    "201": "Quarter",
    "202": "Period",
    "203": "Quarter",
    "214": "Half",
    "216": "Period",
    "217": "Quarter",
    "218": "Set",
    "220": "Half",
    "221": "Half",
    "226": "Quarter",
    "264": "Half"
  },
  "periods": {
    "1": {
      "L_s10": "Regulation Time",
      "h1": "1st 5 Innings",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Inning",
      "s10": "Extra Innings",
      "s2": "2nd Inning",
      "s3": "3rd Inning",
      "s4": "4th Inning",
      "s5": "5th Inning",
      "s6": "6th Inning",
      "s7": "7th Inning",
      "s8": "8th Inning",
      "s9": "9th Inning"
    },
    "2": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "3": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "4": {
      "L_h1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match (Including OT)",
      "s1": "1st Period",
      "s10": "Shootout",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "Overtime",
      "s5": "Shootout",
      "s6": "Shootout",
      "s7": "Shootout",
      "s8": "Shootout",
      "s9": "Shootout"
    },
    "5": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Penalties",
      "s2": "2nd Half",
      "s3": "Extra Time",
      "s4": "Extra Time 2",
      "s5": "Penalties",
      "s6": "Penalties",
      "s7": "Penalties",
      "s8": "Penalties",
      "s9": "Penalties"
    },
    "6": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Round",
      "s10": "Overtime",
      "s2": "2nd Round",
      "s3": "3rd Round",
      "s4": "4th Round",
      "s5": "5th Round",
      "s6": "6th Round",
      "s7": "7th Round",
      "s8": "8th Round",
      "s9": "9th Round"
    },
    "7": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Tournament",
      "s1": "1st Round",
      "s10": "Overtime",
      "s2": "2nd Round",
      "s3": "3rd Round",
      "s4": "4th Round",
      "s5": "5th Round",
      "s6": "6th Round",
      "s7": "7th Round",
      "s8": "8th Round",
      "s9": "9th Round"
    },
    "8": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Set",
      "s10": "Overtime",
      "s2": "2nd Set",
      "s3": "3rd Set",
      "s4": "4th Set",
      "s5": "5th Set",
      "s6": "6th Set",
      "s7": "7th Set",
      "s8": "8th Set",
      "s9": "9th Set"
    },
    "9": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Race",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "10": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Race",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "11": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "13": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Round",
      "s10": "Overtime",
      "s2": "2nd Round",
      "s3": "3rd Round",
      "s4": "4th Round",
      "s5": "5th Round",
      "s6": "6th Round",
      "s7": "7th Round",
      "s8": "8th Round",
      "s9": "9th Round"
    },
    "16": {
      "h1": "NA",
      "h2": "NA",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "NA",
      "s10": "Overtime",
      "s2": "NA",
      "s3": "NA",
      "s4": "NA",
      "s5": "NA",
      "s6": "NA",
      "s7": "NA",
      "s8": "NA",
      "s9": "NA"
    },
    "27": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Round",
      "s10": "Overtime",
      "s2": "2nd Round",
      "s3": "3rd Round",
      "s4": "4th Round",
      "s5": "5th Round",
      "s6": "6th Round",
      "s7": "7th Round",
      "s8": "8th Round",
      "s9": "9th Round"
    },
    "33": {
      "h1": "NFC",
      "h2": "AFC",
      "ht": "Halftime",
      "m": "Champ",
      "s1": "AFC East",
      "s10": "Overtime",
      "s2": "AFC West",
      "s3": "AFC South",
      "s4": "AFC North",
      "s5": "NFC East",
      "s6": "NFC West",
      "s7": "NFC South",
      "s8": "NFC North",
      "s9": "Winning Conference"
    },
    "35": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "East Div",
      "s10": "Overtime",
      "s2": "West Div",
      "s3": "North Div",
      "s4": "Central Div",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "36": {
      "h1": "Eastern Conf",
      "h2": "Western Conf",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "Atlantic Div",
      "s10": "Overtime",
      "s2": "Central Div",
      "s3": "Southwest Div",
      "s4": "Pacific Div",
      "s5": "Southeast Div",
      "s6": "Northwest Div",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "37": {
      "h1": "NL Champ",
      "h2": "AL Champ",
      "ht": "Halftime",
      "m": "World Series Champ",
      "s1": "NL East",
      "s10": "Overtime",
      "s2": "NL West",
      "s3": "NL Central",
      "s4": "AL East",
      "s5": "AL West",
      "s6": "AL Central",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "39": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Winner",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "51": {
      "h1": "NA",
      "h2": "NA",
      "ht": "Halftime",
      "m": "Prop",
      "s1": "NA",
      "s10": "Overtime",
      "s2": "NA",
      "s3": "NA",
      "s4": "NA",
      "s5": "NA",
      "s6": "NA",
      "s7": "NA",
      "s8": "NA",
      "s9": "NA"
    },
    "55": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "63": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Tournament",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "73": {
      "h1": "NA",
      "h2": "NA",
      "ht": "Halftime",
      "m": "Series",
      "s1": "NA",
      "s10": "Overtime",
      "s2": "NA",
      "s3": "NA",
      "s4": "NA",
      "s5": "NA",
      "s6": "NA",
      "s7": "NA",
      "s8": "NA",
      "s9": "NA"
    },
    "74": {
      "h1": "NA",
      "h2": "NA",
      "ht": "Halftime",
      "m": "Series",
      "s1": "NA",
      "s10": "Overtime",
      "s2": "NA",
      "s3": "NA",
      "s4": "NA",
      "s5": "NA",
      "s6": "NA",
      "s7": "NA",
      "s8": "NA",
      "s9": "NA"
    },
    "75": {
      "h1": "NA",
      "h2": "NA",
      "ht": "Halftime",
      "m": "Series",
      "s1": "NA",
      "s10": "Overtime",
      "s2": "NA",
      "s3": "NA",
      "s4": "NA",
      "s5": "NA",
      "s6": "NA",
      "s7": "NA",
      "s8": "NA",
      "s9": "NA"
    },
    "86": {
      "L_s1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "87": {
      "L_h1": "Match 3-Way",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Inns",
      "s10": "Overtime",
      "s2": "2nd Inns",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "88": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Set",
      "s10": "Golden Set",
      "s2": "2nd Set",
      "s3": "3rd Set",
      "s4": "4th Set",
      "s5": "5th Set",
      "s6": "Golden Set",
      "s7": "Golden Set",
      "s8": "Golden Set",
      "s9": "Golden Set"
    },
    "89": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "90": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "92": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "93": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Game",
      "s10": "Overtime",
      "s2": "2nd Game",
      "s3": "3rd Game",
      "s4": "4th Game",
      "s5": "5th Game",
      "s6": "6th Game",
      "s7": "7th Game",
      "s8": "8th Game",
      "s9": "9th Game"
    },
    "94": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "95": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Game",
      "s10": "Overtime",
      "s2": "2nd Game",
      "s3": "3rd Game",
      "s4": "4th Game",
      "s5": "5th Game",
      "s6": "6th Game",
      "s7": "7th Game",
      "s8": "8th Game",
      "s9": "9th Game"
    },
    "98": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Frame",
      "s10": "Overtime",
      "s2": "2nd Frame",
      "s3": "3rd Frame",
      "s4": "4th Frame",
      "s5": "5th Frame",
      "s6": "6th Frame",
      "s7": "7th Frame",
      "s8": "8th Frame",
      "s9": "9th Frame"
    },
    "99": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "101": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Winner",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "102": {
      "L_s1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "103": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "104": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "105": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "110": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Set",
      "s10": "Golden Set",
      "s2": "2nd Set",
      "s3": "3rd Set",
      "s4": "Golden Set",
      "s5": "Golden Set",
      "s6": "Golden Set",
      "s7": "Golden Set",
      "s8": "Golden Set",
      "s9": "Golden Set"
    },
    "113": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "114": {
      "L_h1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Map",
      "s10": "Overtime",
      "s2": "2nd Map",
      "s3": "3rd Map",
      "s4": "4th Map",
      "s5": "5th Map",
      "s6": "6th Map",
      "s7": "7th Map",
      "s8": "8th Map",
      "s9": "9th Map"
    },
    "116": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "118": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "119": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "120": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "121": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Game",
      "s10": "Overtime",
      "s2": "2nd Game",
      "s3": "3rd Game",
      "s4": "4th Game",
      "s5": "5th Game",
      "s6": "6th Game",
      "s7": "7th Game",
      "s8": "8th Game",
      "s9": "9th Game"
    },
    "122": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "124": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Race",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "141": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "142": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "144": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "145": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "159": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "161": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "163": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Overtime",
      "s2": "2nd Half",
      "s3": "Overtime",
      "s4": "Overtime",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "164": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "168": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "169": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "171": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "172": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "173": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Frame",
      "s10": "Overtime",
      "s2": "2nd Frame",
      "s3": "3rd Frame",
      "s4": "4th Frame",
      "s5": "5th Frame",
      "s6": "6th Frame",
      "s7": "7th Frame",
      "s8": "8th Frame",
      "s9": "9th Frame"
    },
    "176": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "177": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "178": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "179": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "180": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "181": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Olympics",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "183": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "185": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "186": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "187": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "188": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "189": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "190": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Inning",
      "s10": "Extra Innings",
      "s2": "2nd Inning",
      "s3": "3rd Inning",
      "s4": "4th Inning",
      "s5": "5th Inning",
      "s6": "6th Inning",
      "s7": "7th Inning",
      "s8": "Extra Innings",
      "s9": "Extra Innings"
    },
    "191": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "192": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "193": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "194": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "197": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "200": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "201": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "202": {
      "L_h1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match (Including OT)",
      "s1": "1st Period",
      "s10": "Shootout",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "Overtime",
      "s5": "Shootout",
      "s6": "Shootout",
      "s7": "Shootout",
      "s8": "Shootout",
      "s9": "Shootout"
    },
    "203": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "204": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "205": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "206": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "207": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "208": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "209": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "213": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    },
    "214": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Penalties",
      "s2": "2nd Half",
      "s3": "Extra Time",
      "s4": "Extra Time 2",
      "s5": "Penalties",
      "s6": "Penalties",
      "s7": "Penalties",
      "s8": "Penalties",
      "s9": "Penalties"
    },
    "216": {
      "L_h1": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match (Including OT)",
      "s1": "1st Period",
      "s10": "Shootout",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "Overtime",
      "s5": "Shootout",
      "s6": "Shootout",
      "s7": "Shootout",
      "s8": "Shootout",
      "s9": "Shootout"
    },
    "217": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "218": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Set",
      "s10": "Overtime",
      "s2": "2nd Set",
      "s3": "3rd Set",
      "s4": "4th Set",
      "s5": "5th Set",
      "s6": "6th Set",
      "s7": "7th Set",
      "s8": "8th Set",
      "s9": "9th Set"
    },
    "220": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Penalties",
      "s2": "2nd Half",
      "s3": "Extra Time",
      "s4": "Extra Time 2",
      "s5": "Penalties",
      "s6": "Penalties",
      "s7": "Penalties",
      "s8": "Penalties",
      "s9": "Penalties"
    },
    "221": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Penalties",
      "s2": "2nd Half",
      "s3": "Extra Time",
      "s4": "Extra Time 2",
      "s5": "Penalties",
      "s6": "Penalties",
      "s7": "Penalties",
      "s8": "Penalties",
      "s9": "Penalties"
    },
    "226": {
      "L_s5": "Regulation Time",
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Game",
      "s1": "1st Quarter",
      "s10": "Overtime",
      "s2": "2nd Quarter",
      "s3": "3rd Quarter",
      "s4": "4th Quarter",
      "s5": "Overtime",
      "s6": "Overtime",
      "s7": "Overtime",
      "s8": "Overtime",
      "s9": "Overtime"
    },
    "264": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Match",
      "s1": "1st Half",
      "s10": "Penalties",
      "s2": "2nd Half",
      "s3": "Extra Time",
      "s4": "Extra Time 2",
      "s5": "Penalties",
      "s6": "Penalties",
      "s7": "Penalties",
      "s8": "Penalties",
      "s9": "Penalties"
    },
    "296": {
      "h1": "1st Half",
      "h2": "2nd Half",
      "ht": "Halftime",
      "m": "Championship",
      "s1": "1st Period",
      "s10": "Overtime",
      "s2": "2nd Period",
      "s3": "3rd Period",
      "s4": "4th Period",
      "s5": "5th Period",
      "s6": "6th Period",
      "s7": "7th Period",
      "s8": "8th Period",
      "s9": "9th Period"
    }
  },
  "abbreviations": {
    "Extra Innings": "Extra",
    "Extra Time": "Ex",
    "Extra Time 2": "Ex 2",
    "Golden Set": "Gld Set",
    "Inning": "Inn",
    "Penalties": "Pen",
    "Period": "Pd",
    "Quarter": "Qtr",
    "Round": "Rd",
    "Tournament": "Trn"
  }
};

const unitByFeed = PANDORA_SPORT_PERIODS.periodUnit;
const periodsByFeed = PANDORA_SPORT_PERIODS.periods;

/** Unit noun for a feed sport (Inning, Set, Game, …) when known. */
export function periodUnitForFeedSport(
  feedSportId: number | string
): string | null {
  return unitByFeed[String(feedSportId)] ?? null;
}

/** Sport-aware period display label from the bake. */
export function bakedPeriodLabel(
  feedSportId: number | string,
  periodCode: string
): string | null {
  const code = periodCode.trim();
  if (!code) return null;
  const map = periodsByFeed[String(feedSportId)];
  if (!map) return null;
  return map[code] ?? map[`L_${code}`] ?? null;
}

export function listBakedPeriodFeedSportIds(): number[] {
  return Object.keys(periodsByFeed)
    .map(Number)
    .filter(n => Number.isFinite(n))
    .sort((a, b) => a - b);
}
