// Offline integrity gate for the local Bun docs cache
// (research/cache/bun-docs, regenerated by bun:docs-index --scope ...).
// The cache is gitignored, so these tests SKIP when it is absent — fresh
// clones stay green; the gate only bites when a stale/broken cache exists.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

const CACHE_DIR = join(import.meta.dir, "..", "research", "cache", "bun-docs");
const INDEX_PATH = join(CACHE_DIR, "INDEX.json");
const DISCOVERY_PATH = join(CACHE_DIR, "DISCOVERY.json");
const hasCache = existsSync(INDEX_PATH) && existsSync(DISCOVERY_PATH);

type IndexEntry = { name: string; source: string; sourceUrl: string; bytes: number; ok: boolean };

describe.skipIf(!hasCache)("bun-docs cache integrity", () => {
  test("INDEX.json tracks bundler/plugins.mdx with ok=true", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as { pages: IndexEntry[] };
    const bp = idx.pages.find((p) => p.name === "bundler-plugins");
    expect(bp).toBeDefined();
    expect(bp!.sourceUrl).toContain("docs/bundler/plugins.mdx");
    expect(bp!.ok).toBe(true);
  });

  test("cached bundler-plugins.mdx carries the Namespaces section", () => {
    const mdx = readFileSync(join(CACHE_DIR, "bundler-plugins.mdx"), "utf8");
    expect(mdx).toContain("## Namespaces");
    expect(mdx).toContain('The default namespace is `"file"`');
    expect(mdx).toContain('namespace: "yaml:"');
  });

  test("INDEX page names are unique and every ok entry has a cached file", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as { pages: IndexEntry[] };
    const names = idx.pages.map((p) => p.name);
    expect(new Set(names).size).toBe(names.length);
    for (const p of idx.pages) {
      if (p.ok) expect(existsSync(join(CACHE_DIR, p.name + ".mdx")), p.name).toBe(true);
    }
  });

  test("INDEX.json carries the maps.toml triple-lock hash (written by docs:refresh)", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as Record<string, unknown>;
    expect(typeof idx.mapsHash).toBe("string");
    expect(idx.mapsHash as string).toMatch(/^[0-9a-f]{16}$/);
    const meta = idx.mapsMeta as Record<string, unknown> | undefined;
    expect(meta?.bunVersion).toBeTruthy();
    expect(meta?.tagRef).toBe("bun-v" + Bun.version);
  });

  test("DISCOVERY.json records per-scope page lists incl. bundler", () => {
    const disc = JSON.parse(readFileSync(DISCOVERY_PATH, "utf8")) as {
      scopes: Record<string, Array<{ name: string; path: string }>>;
    };
    expect(disc.scopes).toBeDefined();
    expect(disc.scopes.all.some((p) => p.path === "bundler/plugins.mdx")).toBe(true);
    expect(disc.scopes.bundler.some((p) => p.path === "bundler/plugins.mdx")).toBe(true);
  });
});
