// Offline integrity gate for the local Bun docs cache
// (research/cache/bun-docs, regenerated by bun:docs-index from the TRUE index
// bun.com/llm.txt — Bun's official LLM-oriented docs map; see AGENT-PITFALLS §9).
// The cache is gitignored, so these tests SKIP when it is absent — fresh
// clones stay green; the gate only bites when a stale/broken cache exists.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

const CACHE_DIR = join(import.meta.dir, "..", "research", "cache", "bun-docs");
const INDEX_PATH = join(CACHE_DIR, "INDEX.json");
const DISCOVERY_PATH = join(CACHE_DIR, "DISCOVERY.json");
const hasCache = existsSync(INDEX_PATH) && existsSync(DISCOVERY_PATH);

type IndexEntry = { name: string; source: string; sourceUrl: string; bytes: number; ok: boolean };

describe.skipIf(!hasCache)("bun-docs cache integrity (llm.txt index)", () => {
  test("INDEX.json tracks bundler/plugins.md with ok=true", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as { pages: IndexEntry[] };
    const bp = idx.pages.find((p) => p.name === "bundler-plugins");
    expect(bp).toBeDefined();
    expect(bp!.sourceUrl).toBe("https://bun.com/docs/bundler/plugins.md");
    expect(bp!.source).toBe("llm");
    expect(bp!.ok).toBe(true);
  });

  test("cached bundler-plugins.md carries the Namespaces section", () => {
    const md = readFileSync(join(CACHE_DIR, "bundler-plugins.md"), "utf8");
    expect(md).toContain("## Namespaces");
    expect(md).toContain('The default namespace is `"file"`');
    expect(md).toContain('namespace: "yaml:"');
  });

  test("INDEX page names are unique and every ok entry has a cached .md file", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as { pages: IndexEntry[] };
    const names = idx.pages.map((p) => p.name);
    expect(new Set(names).size).toBe(names.length);
    for (const p of idx.pages) {
      if (p.ok) expect(existsSync(join(CACHE_DIR, p.name + ".md")), p.name).toBe(true);
    }
  });

  test("INDEX.json carries the maps.toml triple-lock hash (written by docs:refresh)", () => {
    const idx = JSON.parse(readFileSync(INDEX_PATH, "utf8")) as Record<string, unknown>;
    expect(typeof idx.mapsHash).toBe("string");
    expect(idx.mapsHash as string).toMatch(/^[0-9a-f]{16}$/);
    const meta = idx.mapsMeta as Record<string, unknown> | undefined;
    expect(meta?.bunVersion).toBeTruthy();
    expect(meta?.source).toBe("llm");
    expect(meta?.ref).toMatch(/^llm#[0-9a-f]{16}$/);
  });

  test("DISCOVERY.json records the single llm.txt page list", () => {
    const disc = JSON.parse(readFileSync(DISCOVERY_PATH, "utf8")) as {
      source: string;
      llmUrl: string;
      llmHash: string;
      pages: Array<{ name: string; url: string }>;
    };
    expect(disc.source).toBe("llm");
    expect(disc.llmUrl).toBe("https://bun.com/llm.txt");
    expect(disc.llmHash).toMatch(/^[0-9a-f]{16}$/);
    expect(disc.pages.length).toBeGreaterThan(0);
    expect(disc.pages.some((p) => p.name === "bundler-plugins" && p.url === "https://bun.com/docs/bundler/plugins.md")).toBe(true);
    expect(new Set(disc.pages.map((p) => p.name)).size).toBe(disc.pages.length);
  });
});
