#!/usr/bin/env bun
/**
 * Reporter for the reference cross-check (178): deterministic JSON report +
 * a 9 section appended to docs/BUN_BUILD_FINDINGS.md. No timestamps so the
 * artifacts are byte-stable across runs (same convention as the evidence).
 */
import type { CheckResult, CoverageGap } from './compare.ts';

const BTK = String.fromCharCode(96);

export interface CrossCheckMeta {
  bunVersion: string;
  bunRevision: string;
  bundleHash: string;
}

export async function writeJsonReport(path: string, checks: CheckResult[], gaps: CoverageGap[], meta: CrossCheckMeta): Promise<void> {
  const counts: Record<string, number> = {};
  for (const c of checks) counts[c.verdict] = (counts[c.verdict] ?? 0) + 1;
  const report = {
    tool: 'tools/reference-cross-check',
    bunVersion: meta.bunVersion,
    bunRevision: meta.bunRevision,
    bundleHash: meta.bundleHash,
    verdictCounts: counts,
    checks: checks.map((c) => ({
      id: c.claim.id,
      api: c.claim.api,
      source: c.claim.source,
      docSays: c.claim.docSays,
      observed: c.observed,
      verdict: c.verdict,
    })),
    coverageGaps: gaps.map((g) => ({ surface: g.surface, gaps: g.gaps })),
  };
  await Bun.write(path, JSON.stringify(report, null, 2) + '\n');
}

const SURFACES: [string, string][] = [
  ['BA', 'BuildArtifact'],
  ['BC', 'BuildConfig'],
  ['IM', 'Bun.Image'],
  ['SV', 'Bun.serve'],
  ['SQ', 'bun:sqlite'],
  ['UP', 'URLPattern'],
];

export function renderSection9(checks: CheckResult[], gaps: CoverageGap[], meta: CrossCheckMeta): string {
  const L: string[] = [];
  const row = (c: CheckResult) => {
    const obs = typeof c.observed === 'string' ? c.observed : JSON.stringify(c.observed);
    return '| ' + BTK + c.claim.id + BTK + ' | ' + BTK + c.claim.api + BTK + ' | ' + BTK + c.claim.source + BTK + ' | ' + c.claim.docSays + ' | ' + (obs ?? '').slice(0, 90) + ' | ' + c.verdict + ' |';
  };
  L.push('## 9. Reference cross-check — official bun-types docs vs observed evidence');
  L.push('');
  L.push('Regenerated by ' + BTK + 'bun run reference-cross-check' + BTK + ' (tools/reference-cross-check, §178).');
  L.push('Sources: bundled bun-types@' + meta.bunVersion + ' (' + meta.bundleHash + ') docs + ' + BTK + 'bun.d.ts' + BTK + ', compared against');
  L.push('' + BTK + 'tools/build-artifact-evidence.json' + BTK + '. Verdicts: CONSISTENT (doc + observed agree),');
  L.push('PINNED-DISCREPANCY (doc says X, observed Y — our correction), DOC-CHANGED (fragment missing —');
  L.push('the pin premise moved; re-verify), NO-EVIDENCE (ledger path broken).');
  L.push('');
  const vc: Record<string, number> = {};
  for (const c of checks) vc[c.verdict] = (vc[c.verdict] ?? 0) + 1;
  L.push('**Verdict summary:** ' + checks.length + ' claims · ' + (vc['CONSISTENT'] ?? 0) + ' CONSISTENT · ' + (vc['PINNED-DISCREPANCY'] ?? 0) + ' PINNED-DISCREPANCY · ' + (vc['DOC-CHANGED'] ?? 0) + ' DOC-CHANGED · ' + (vc['NO-EVIDENCE'] ?? 0) + ' NO-EVIDENCE.');
  L.push('');
  const bySurface = (prefix: string) => checks.filter((c) => c.claim.id.startsWith(prefix));
  for (const [prefix, name] of SURFACES) {
    const rows = bySurface(prefix);
    if (!rows.length) continue;
    L.push('### ' + name);
    L.push('');
    L.push('| Claim | API | Source | Doc says | Observed | Verdict |');
    L.push('|---|---|---|---|---|---|');
    for (const c of rows) L.push(row(c));
    L.push('');
  }
  if (gaps.length) {
    L.push('### Coverage gaps — declared but not evidence-grounded');
    L.push('');
    for (const g of gaps) L.push('- ' + BTK + g.surface + BTK + ': ' + g.gaps.join(', '));
    L.push('');
  } else {
    L.push('No coverage gaps: every declared option on the grounded surfaces has evidence.');
    L.push('');
  }
  return L.join('\n');
}

export async function appendSection9(docPath: string, section: string): Promise<boolean> {
  const doc = await Bun.file(docPath).text();
  const cut = doc.indexOf('## 9.');
  const head = cut >= 0 ? doc.slice(0, cut).replace(/\n+$/, '') + '\n' : doc.replace(/\n+$/, '') + '\n';
  const updated = head + section + '\n';
  const changed = updated !== doc;
  await Bun.write(docPath, updated);
  return changed;
}

export {};