#!/usr/bin/env bun
/**
 * Generate color-system artifacts from the Bun-native kernel.
 *
 * Outputs:
 *   - public/colors.css                  CSS custom properties
 *   - public/registry/color-system.json  design-tool registry
 *   - docs/COLORS.md                     markdown swatch table
 *   - docs/COLORS.html                   Bun.markdown HTML
 *   - artifacts/color-preview.txt        ANSI terminal preview
 *   - src/research/hq-app/color-vars.css co-located HQ copy
 *
 *   bun run colors:artifacts
 *   bun run colors:check     # fail if committed artifacts drift from kernel
 *
 * @see https://bun.com/docs/runtime/color#flexible-input
 * @see https://bun.com/docs/runtime/file-io#writing-files-bun-write
 * @see https://bun.com/docs/runtime/markdown#bun-markdown-html
 * @see https://bun.com/docs/runtime/markdown#options
 * @see src/lib/color/kernel.ts
 * @see src/lib/markdown.ts
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { markdownToHtml } from "../src/lib/markdown.ts";
import { parseArgs } from "node:util";
import {
  COLORS,
  ansi16mColor,
  colorNumber,
  contrast,
  cssColor,
  foregroundCss,
  hexColor,
  isDark,
  luminance,
  paint,
  rgbChannels,
  type ColorKey,
} from "../src/lib/color/index.ts";
import { TOKENS, baseCssVars } from "../src/institutions/design-tokens.ts";

const root = join(import.meta.dir, "..");
const { values: cav2 } = parseArgs({ args: Bun.argv.slice(2), options: { check: { type: 'boolean' } }, strict: false, allowPositionals: true });
const checkOnly = cav2.check === true;

const keys = Object.keys(COLORS) as ColorKey[];
const venueKeys: ColorKey[] = [
  "kalshi",
  "polymarket",
  "pinnacle",
  "betfair",
  "unknown",
];
const semverKeys: ColorKey[] = [
  "semverMajor",
  "semverMinor",
  "semverPatch",
  "selected",
];
const domainKeys = keys.filter(
  (k) => !venueKeys.includes(k) && !semverKeys.includes(k),
);

function buildCssVars(): string {
  let cssVars =
    "/* Generated by scripts/generate-color-artifacts.ts — do not edit */\n:root {\n";
  for (const key of keys) {
    cssVars += `  --color-${key}: ${cssColor(key)};\n`;
    cssVars += `  --color-${key}-on: ${foregroundCss(key)};\n`;
  }
  cssVars += "}\n";
  return cssVars;
}

/**
 * Semantic token vars (:root) generated from TOKENS via baseCssVars().
 * hq-app/styles.css does NOT hand-write these - index.html links this
 * generated file (drift-checked by colors:check).
 */
function buildTokenVars(): string {
  return '/* Generated by scripts/generate-color-artifacts.ts — do not edit */\n' + baseCssVars() + '\n';
}

/** Markdown doc for the design tokens (TOKENS), regenerated from source. */
function buildTokensDoc(): string {
  const rows: string[] = [];
  const walk = (obj: Record<string, unknown>, path: string) => {
    for (const [k, v] of Object.entries(obj)) {
      const p = path ? path + '.' + k : k;
      if (typeof v === 'string') rows.push('| `' + p + '` | ' + v.replace(/\|/g, '\\|') + ' |');
      else walk(v as Record<string, unknown>, p);
    }
  };
  walk(TOKENS as Record<string, unknown>, '');
  return [
    '# Design tokens (TOKENS) — generated, do not edit',
    '',
    'Regenerated by `bun run colors:artifacts` from `src/institutions/design-tokens.ts`.',
    '',
    '| Path | Value |',
    '| ---- | ----- |',
    ...rows,
    '',
  ].join('\n');
}

function buildRegistryBody(): string {
  const registry = Object.fromEntries(
    keys.map((key) => [
      key,
      {
        hex: hexColor(key),
        css: cssColor(key),
        number: colorNumber(key),
        rgb: rgbChannels(key),
        foregroundCss: foregroundCss(key),
        luminance: Number(luminance(key).toFixed(4)),
        isDark: isDark(key),
      },
    ]),
  );
  // Stable body for --check (strip generatedAt)
  return JSON.stringify(
    {
      schemaVersion: 1,
      keys,
      venueKeys,
      domainKeys,
      semverKeys,
      colors: registry,
    },
    null,
    2,
  ) + "\n";
}

function ansiBg(key: ColorKey): string {
  return ansi16mColor(key).replace("38", "48");
}

function swatchBlock(key: ColorKey, width = 20): string {
  const bg = ansiBg(key);
  if (!bg) return "█".repeat(width);
  return `${bg}${"█".repeat(width)}\x1b[0m`;
}

function markdownRow(key: ColorKey): string {
  const lum = luminance(key);
  const vsWhite = (1.0 + 0.05) / (lum + 0.05);
  const vsBlack = (lum + 0.05) / 0.05;
  const wIcon = vsWhite >= 4.5 ? (vsWhite >= 7 ? " ✅✅" : " ✅") : "";
  const bIcon = vsBlack >= 4.5 ? (vsBlack >= 7 ? " ✅✅" : " ✅") : "";
  return (
    `| **${key}** | \`${hexColor(key)}\` | ${swatchBlock(key)} | ` +
    `${lum.toFixed(2)} | ${vsWhite.toFixed(1)}:1${wIcon} | ${vsBlack.toFixed(1)}:1${bIcon} | ` +
    `\`${foregroundCss(key)}\` |`
  );
}

function buildMarkdown(): string {
  const tableHeader =
    `| Name | Hex | Swatch | Lum. | Contrast (white) | Contrast (black) | On-color |
|------|-----|--------|------|------------------|------------------|----------|`;

  const usageTs = [
    "```ts",
    'import { cssColor, foregroundCss, paint } from "../src/lib/color/index.ts";',
    "",
    'cssColor("trading")           // → "#e74c3c"',
    'foregroundCss("trading")      // → "#ffffff"',
    'paint("risk", "trading")      // → ANSI-colored text',
    "```",
  ].join("\n");

  return [
    "# Color Palette",
    "",
    "> Generated from `src/lib/color/` — Bun-native kernel SSOT",
    '> Terminal swatches use `Bun.color(hex, "ansi-16m")` for true-color output',
    "",
    "## Venue Colors",
    "",
    tableHeader,
    ...venueKeys.map(markdownRow),
    "",
    "## Domain Colors",
    "",
    tableHeader,
    ...domainKeys.map(markdownRow),
    "",
    "## Semver / `bun update -i`",
    "",
    tableHeader,
    ...semverKeys.map(markdownRow),
    "",
    "- ✅ Meets WCAG AA for normal text (4.5:1) on white or black background.",
    "- ✅✅ Meets WCAG AAA (7:1).",
    "- `luminance` and `contrast` calculated per WCAG 2.1 sRGB.",
    `- Sample contrast(trading, misc) = ${contrast("trading", "misc").toFixed(1)}`,
    "",
    "## Usage",
    "",
    usageTs,
    "",
  ].join("\n") + "\n";
}

function buildPreview(): string {
  return (
    keys
      .map((key) => {
        const label = key.padEnd(12);
        const hex = hexColor(key).padEnd(9);
        const on = foregroundCss(key);
        return `${paint(`  ${label}${hex} on=${on}  `, key, "deterministic")}`;
      })
      .join("\n") + "\n"
  );
}

/** Compare stable artifact bodies (JSON without generatedAt). */
async function checkArtifacts(): Promise<string[]> {
  const errs: string[] = [];
  const cssExpected = buildCssVars();
  const cssPath = join(root, "public/colors.css");
  const cssActual = (await Bun.file(cssPath).exists())
    ? await Bun.file(cssPath).text()
    : "";
  if (cssActual !== cssExpected) {
    errs.push("public/colors.css stale — run bun run colors:artifacts");
  }

  const hqCssPath = join(root, "src/research/hq-app/color-vars.css");
  const hqCss = (await Bun.file(hqCssPath).exists())
    ? await Bun.file(hqCssPath).text()
    : "";
  if (hqCss !== cssExpected) {
    errs.push("src/research/hq-app/color-vars.css stale — run bun run colors:artifacts");
  }

  const regPath = join(root, "public/registry/color-system.json");
  if (!(await Bun.file(regPath).exists())) {
    errs.push("public/registry/color-system.json missing — run bun run colors:artifacts");
  } else {
    const onDisk = await Bun.file(regPath).json() as {
      generatedAt?: string;
      [k: string]: unknown;
    };
    const { generatedAt: _g, ...rest } = onDisk;
    const expected = JSON.parse(buildRegistryBody()) as Record<string, unknown>;
    if (!Bun.deepEquals(rest, expected, true)) {
      errs.push("public/registry/color-system.json stale — run bun run colors:artifacts");
    }
  }

  const mdPath = join(root, "docs/COLORS.md");
  const mdExpected = buildMarkdown();
  const mdActual = (await Bun.file(mdPath).exists())
    ? await Bun.file(mdPath).text()
    : "";
  if (mdActual !== mdExpected) {
    errs.push("docs/COLORS.md stale — run bun run colors:artifacts");
  const tokenVarsPath = join(root, "src/research/hq-app/token-vars.css");
  const tokenVars = (await Bun.file(tokenVarsPath).exists()) ? await Bun.file(tokenVarsPath).text() : "";
  if (tokenVars !== buildTokenVars()) {
    errs.push("src/research/hq-app/token-vars.css stale — run bun run colors:artifacts");
  }
  const tokensDocPath = join(root, "docs/TOKENS.md");
  const tokensDoc = (await Bun.file(tokensDocPath).exists()) ? await Bun.file(tokensDocPath).text() : "";
  if (tokensDoc !== buildTokensDoc()) {
    errs.push("docs/TOKENS.md stale — run bun run colors:artifacts");
  }
  }

  return errs;
}

async function writeArtifacts(): Promise<void> {
  mkdirSync(join(root, "public/registry"), { recursive: true });
  mkdirSync(join(root, "artifacts"), { recursive: true });
  mkdirSync(join(root, "docs"), { recursive: true });
  mkdirSync(join(root, "src/research/hq-app"), { recursive: true });

  const cssVars = buildCssVars();
  await Bun.write(join(root, "public/colors.css"), cssVars);
  await Bun.write(join(root, "src/research/hq-app/color-vars.css"), cssVars);

  const registryBody = JSON.parse(buildRegistryBody()) as Record<string, unknown>;
  await Bun.write(
    join(root, "public/registry/color-system.json"),
    JSON.stringify(
      { ...registryBody, generatedAt: new Date().toISOString() },
      null,
      2,
    ) + "\n",
  );

  const md = buildMarkdown();
  await Bun.write(join(root, "docs/COLORS.md"), md);
  await Bun.write(join(root, "docs/COLORS.html"), markdownToHtml(md));
  await Bun.write(join(root, "artifacts/color-preview.txt"), buildPreview());
  await Bun.write(join(root, "src/research/hq-app/token-vars.css"), buildTokenVars());
  await Bun.write(join(root, "docs/TOKENS.md"), buildTokensDoc());

  console.log(
    `✅ color artifacts — ${keys.length} keys → public/colors.css, public/registry/color-system.json, docs/COLORS.{md,html}, docs/TOKENS.md, hq-app/{color-vars,token-vars}.css, artifacts/color-preview.txt`,
  );
}

if (checkOnly) {
  const errs = await checkArtifacts();
  if (errs.length) {
    console.error("colors:check FAIL");
    for (const e of errs) console.error(" ", e);
    process.exit(1);
  }
  console.log(`colors:check OK — ${keys.length} keys match committed artifacts`);
} else {
  await writeArtifacts();
}
