#!/usr/bin/env bun
/**
 * Generate color-system artifacts from the Bun-native kernel.
 *
 * Outputs:
 *   - public/colors.css                  CSS custom properties
 *   - public/registry/color-system.json  design-tool registry
 *   - docs/COLORS.md                     markdown swatch table
 *   - docs/COLORS.html                   Bun.markdown HTML
 *   - artifacts/color-preview.txt        ANSI terminal preview
 *
 * Run: bun run colors:artifacts
 *
 * @see https://bun.com/docs/runtime/color#flexible-input
 * @see https://bun.com/docs/runtime/file-io#writing-files-bun-write
 * @see https://bun.com/docs/runtime/markdown#bun-markdown-html
 * @see src/lib/color/kernel.ts
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import {
  COLORS,
  ansi16mColor,
  colorNumber,
  contrast,
  cssColor,
  foregroundCss,
  hexColor,
  isDark,
  luminance,
  paint,
  rgbChannels,
  type ColorKey,
} from "../src/lib/color/index.ts";

const root = join(import.meta.dir, "..");
const keys = Object.keys(COLORS) as ColorKey[];
const venueKeys: ColorKey[] = [
  "kalshi",
  "polymarket",
  "pinnacle",
  "betfair",
  "unknown",
];
const semverKeys: ColorKey[] = [
  "semverMajor",
  "semverMinor",
  "semverPatch",
  "selected",
];
const domainKeys = keys.filter(
  (k) => !venueKeys.includes(k) && !semverKeys.includes(k),
);

mkdirSync(join(root, "public/registry"), { recursive: true });
mkdirSync(join(root, "artifacts"), { recursive: true });
mkdirSync(join(root, "docs"), { recursive: true });

// ── 1. CSS custom properties ─────────────────────────────────────
let cssVars = "/* Generated by scripts/generate-color-artifacts.ts — do not edit */\n:root {\n";
for (const key of keys) {
  cssVars += `  --color-${key}: ${cssColor(key)};\n`;
  cssVars += `  --color-${key}-on: ${foregroundCss(key)};\n`;
}
cssVars += "}\n";
await Bun.write(join(root, "public/colors.css"), cssVars);
// HQ HTML import can link a co-located copy (bundler-friendly relative href).
await Bun.write(join(root, "src/research/hq-app/color-vars.css"), cssVars);

// ── 2. Registry JSON ─────────────────────────────────────────────
const registry = Object.fromEntries(
  keys.map((key) => [
    key,
    {
      hex: hexColor(key),
      css: cssColor(key),
      number: colorNumber(key),
      rgb: rgbChannels(key),
      foregroundCss: foregroundCss(key),
      luminance: Number(luminance(key).toFixed(4)),
      isDark: isDark(key),
    },
  ]),
);
await Bun.write(
  join(root, "public/registry/color-system.json"),
  JSON.stringify(
    {
      schemaVersion: 1,
      generatedAt: new Date().toISOString(),
      keys,
      venueKeys,
      domainKeys,
      semverKeys,
      colors: registry,
    },
    null,
    2,
  ) + "\n",
);

// ── 3. Markdown + HTML docs ──────────────────────────────────────
function ansiBg(key: ColorKey): string {
  return ansi16mColor(key).replace("38", "48");
}

function swatchBlock(key: ColorKey, width = 20): string {
  const bg = ansiBg(key);
  if (!bg) return "█".repeat(width);
  return `${bg}${"█".repeat(width)}\x1b[0m`;
}

function markdownRow(key: ColorKey): string {
  const lum = luminance(key);
  const vsWhite = (1.0 + 0.05) / (lum + 0.05);
  const vsBlack = (lum + 0.05) / 0.05;
  const wIcon = vsWhite >= 4.5 ? (vsWhite >= 7 ? " ✅✅" : " ✅") : "";
  const bIcon = vsBlack >= 4.5 ? (vsBlack >= 7 ? " ✅✅" : " ✅") : "";
  return (
    `| **${key}** | \`${hexColor(key)}\` | ${swatchBlock(key)} | ` +
    `${lum.toFixed(2)} | ${vsWhite.toFixed(1)}:1${wIcon} | ${vsBlack.toFixed(1)}:1${bIcon} | ` +
    `\`${foregroundCss(key)}\` |`
  );
}

const tableHeader =
  `| Name | Hex | Swatch | Lum. | Contrast (white) | Contrast (black) | On-color |
|------|-----|--------|------|------------------|------------------|----------|`;

const usageTs = [
  "```typescript",
  'import { cssColor, foregroundCss, paint } from "../src/lib/color/index.ts";',
  "",
  'cssColor("trading")           // → "#e74c3c"',
  'foregroundCss("trading")      // → "#ffffff"',
  'paint("risk", "trading")      // → ANSI-colored text',
  "```",
].join("\n");

const md = [
  "# Color Palette",
  "",
  "> Generated from `src/lib/color/` — Bun-native kernel SSOT",
  '> Terminal swatches use `Bun.color(hex, "ansi-16m")` for true-color output',
  "",
  "## Venue Colors",
  "",
  tableHeader,
  ...venueKeys.map(markdownRow),
  "",
  "## Domain Colors",
  "",
  tableHeader,
  ...domainKeys.map(markdownRow),
  "",
  "## Semver / `bun update -i`",
  "",
  tableHeader,
  ...semverKeys.map(markdownRow),
  "",
  "- ✅ Meets WCAG AA for normal text (4.5:1) on white or black background.",
  "- ✅✅ Meets WCAG AAA (7:1).",
  "- `luminance` and `contrast` calculated per WCAG 2.1 sRGB.",
  `- Sample contrast(trading, misc) = ${contrast("trading", "misc").toFixed(1)}`,
  "",
  "## Usage",
  "",
  usageTs,
  "",
].join("\n");

await Bun.write(join(root, "docs/COLORS.md"), md + "\n");
await Bun.write(join(root, "docs/COLORS.html"), Bun.markdown.html(md));

// ── 4. ANSI terminal preview ─────────────────────────────────────
const preview = keys
  .map((key) => {
    const label = key.padEnd(12);
    const hex = hexColor(key).padEnd(9);
    const on = foregroundCss(key);
    return `${paint(`  ${label}${hex} on=${on}  `, key, "deterministic")}`;
  })
  .join("\n");
await Bun.write(join(root, "artifacts/color-preview.txt"), preview + "\n");

console.log(
  `✅ color artifacts — ${keys.length} keys → public/colors.css, public/registry/color-system.json, docs/COLORS.{md,html}, artifacts/color-preview.txt`,
);
