#!/usr/bin/env bun
/**
 * Generate strict union types from the canonical glossary.
 *
 * Run after adding/removing glossary entries:
 *   bun scripts/generate-glossary-types.ts
 *
 * Produces src/generated/glossary-ids.ts with:
 *   - GlossaryId       — all ids
 *   - RegistryId       — kind="registry" ids
 *   - UiId             — kind="ui" ids
 *   - CompositeId      — kind="composite" ids
 *
 * @see src/institutions/glossary.ts
 */
import { GLOSSARY_ENTRIES, type GlossaryKind } from "../src/institutions/glossary.ts";

const byKind = (k: GlossaryKind) =>
  GLOSSARY_ENTRIES.filter((e) => e.kind === k).map((e) => e.id);

const union = (ids: string[]) =>
  ids.length > 0 ? ids.map((id) => `"${id}"`).join(" | ") : "never";

const allIds = GLOSSARY_ENTRIES.map((e) => e.id);
const registryIds = byKind("registry");
const uiIds = byKind("ui");
const compositeIds = byKind("composite");

const content = [
  "// Auto-generated by scripts/generate-glossary-types.ts — DO NOT EDIT.",
  `// ${allIds.length} glossary entries (${registryIds.length} registry, ${uiIds.length} ui, ${compositeIds.length} composite)`,
  "",
  `export type GlossaryId = ${union(allIds)};`,
  `export type RegistryId = ${union(registryIds)};`,
  `export type UiId = ${union(uiIds)};`,
  `export type CompositeId = ${union(compositeIds)};`,
  "",
].join("\n");

await Bun.write("src/generated/glossary-ids.ts", content + "\n");

console.log(`✅ Generated src/generated/glossary-ids.ts`);
console.log(`   ${allIds.length} GlossaryId entries`);
console.log(`   ${registryIds.length} RegistryId entries`);
console.log(`   ${uiIds.length} UiId entries`);
console.log(`   ${compositeIds.length} CompositeId entries`);
