#!/usr/bin/env bun
/**
 * bun run build-artifact:findings - regenerate docs/BUN_BUILD_FINDINGS.md
 * from tools/build-artifact-evidence.json (AGENT-PITFALLS 177 refactor).
 * The doc renders OBSERVED values from the evidence file (live 1.4.0
 * builds in scratch/art-ground/) - nothing is asserted from memory.
 */
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const EVIDENCE = join(ROOT, 'tools', 'build-artifact-evidence.json');
const DOC = join(ROOT, 'docs', 'BUN_BUILD_FINDINGS.md');
const BTK = String.fromCharCode(96);
const ev = JSON.parse(await Bun.file(EVIDENCE).text());
const s = (n: string) => ev.scenarios.find((x: any) => x.name === n);
const short = ev.bunRevision.slice(0, 9);

// ---- helpers ----
const outRow = (o: any) => [
  BTK + o.path + BTK,
  BTK + o.kind + BTK,
  o.hash === 'null' ? BTK + 'null' + BTK : BTK + o.hash + BTK,
  BTK + o.loader + BTK,
  String(o.size),
  BTK + o.type + BTK,
  BTK + o.sourcemap + BTK,
].join(' | ');
const configCell = (c: any) => Object.entries(c).map(([k, v]) => BTK + k + BTK + ' ' + JSON.stringify(v)).join(' · ');

const md: string[] = [];
const L = (x: string = '') => { md.push(x); };

L('# Bun Build Findings — 9 grounded surfaces, pinned on 1.4.0');
L();
L('Regenerated by ' + BTK + 'bun run build-artifact:findings' + BTK + ' (tools/build-artifact-findings.ts, §177).');
L('Grounding evidence: ' + BTK + 'tools/build-artifact-evidence.json' + BTK + ' — captured by');
L('' + BTK + 'bun run build-artifact:evidence' + BTK + ' from LIVE ' + BTK + 'Bun.build()' + BTK + ' runs in');
L('' + BTK + 'scratch/art-ground/' + BTK + ' on Bun ' + ev.bunVersion + ' (' + short + '). Every value below was');
L('OBSERVED, not assumed; docs claims are compared against these artifacts, never the reverse.');
L();
L('## 1. BuildArtifact — read-only output surface (result.outputs[i])');
L();
L('| Property | Type (bun-types 1.4.0) | Observed on 1.4.0 (evidence) |');
L('|---|---|---|');
const s01 = s('S01-artifact-surface');
const s01entry = s01.outputs.find((o: any) => o.kind === 'entry-point');
const s01css = s01.outputs.find((o: any) => o.kind === 'asset');
const s02 = s('S02-no-outdir');
const s03 = s('S03-splitting');
const s04l = s('S04-sourcemap-linked');
const s04x = s('S04-sourcemap-external');
const s04i = s('S04-sourcemap-inline');
const s06 = s('S06-bytecode');
const s17 = s('S17-publicPath');
const s19 = s('S19-outfile');
L('| kind | ' + BTK + "'entry-point' | 'chunk' | 'asset' | 'sourcemap' | 'bytecode'" + BTK + ' | all five observed: entry-point + asset (S01), chunk (S03), sourcemap (S04), bytecode (S06) |');
L('| path | string | with outdir: absolute path under outdir, written (S01); without: bare ' + BTK + './entry.js' + BTK + ', NOT written (S02); outfile: ignored by the API — bare name, NOT written (S19) |');
L('| loader | Loader | reflects the SOURCE loader: ' + BTK + "'ts'" + BTK + ' for a .ts entry (S01), ' + BTK + "'file'" + BTK + ' for a .png asset (S17) and for .map artifacts (S04); CSS asset reports ' + BTK + "'ts'" + BTK + ' on 1.4.0 (S01 quirk) |');
L('| hash | string | null | non-null for entry/chunk/asset (' + s01entry.hash + ', ' + s03.outputs.find((o: any) => o.kind === 'chunk').hash + '); ' + BTK + "'00000000'" + BTK + ' placeholder for sourcemap artifacts (S04); identical across sourcemap modes despite different output bytes (' + s04l.outputs[0].hash + ' @ 215B/182B/705B, S04) |');
L('| sourcemap | BuildArtifact | null | linked/external: nested artifact pointing at the .map (S04); inline: ' + BTK + 'null' + BTK + ' (map base64-embedded); none: no map, no nested artifact (S04) |');
L('| size (Blob) | number | ' + s01entry.size + ' entry (S01), ' + s01css.size + ' css asset (S01), ' + s17.outputs.find((o: any) => o.kind === 'asset').size + ' png asset (S17), ' + s04l.outputs.find((o: any) => o.kind === 'sourcemap').size + ' .map (S04) |');
L('| type (Blob) | string | ' + BTK + s01entry.type + BTK + ' entry (S01), ' + BTK + s01css.type + BTK + ' css asset (S01), ' + BTK + s17.outputs.find((o: any) => o.kind === 'asset').type + BTK + ' png (S17), ' + BTK + s04l.outputs.find((o: any) => o.kind === 'sourcemap').type + BTK + ' .map (S04) |');
L();
L('Methods (S01): ' + BTK + '.text()' + BTK + ' ' + BTK + '.arrayBuffer()' + BTK + ' ' + BTK + '.stream()' + BTK + ' ' + BTK + '.json()' + BTK + ' ' + BTK + '.slice()' + BTK + ' present; ' + BTK + '.formData()' + BTK + ' ' + BTK + '.image()' + BTK + ' ' + BTK + '.bytes()' + BTK + ' ABSENT on 1.4.0; ' + BTK + 'instanceof Blob' + BTK + ' = false (Blob-CONFORMANT, not a Blob). ' + BTK + '.slice()' + BTK + ' returns a PLAIN Blob (see §6).');
L();
L('## 2. BuildConfig — input options (passed to Bun.build())');
L();
L('| Option | Type (bun-types 1.4.0) | Observed effect on 1.4.0 (evidence) |');
L('|---|---|---|');
const s05a = s('S05a-naming-string');
const s05b = s('S05b-naming-object');
const s05c = s('S05c-naming-hashless-collision');
const s07a = s('S07a-compile-outdir');
const s07b = s('S07b-compile-string-bun');
const s07c = s('S07c-compile-true-outfile');
const s07d = s('S07d-compile-object-outfile');
const s11 = s('S11-define');
const s12 = s('S12-env-inline');
const s13a = s('S13a-drop-off');
const s13b = s('S13b-drop-on');
const s14e = s('S14-allowUnresolved-empty');
const s14g = s('S14-allowUnresolved-glob');
const s15a = s('S15a-external-zod');
const s15b = s('S15b-bundle-zod');
const s16a = s('S16a-conditions-default');
const s16b = s('S16b-conditions-custom');
const s18a = s('S18a-root-unset');
const s18b = s('S18b-root-set');
L('| entrypoints | string[] (required) | multi-entry + ' + BTK + 'splitting: true' + BTK + ' → one output per entry + a shared chunk (S03: ' + s03.outputs.filter((o: any) => o.kind === 'entry-point').length + ' entry-points + 1 chunk + 1 asset) |');
L('| outdir | string | outputs written under outdir, absolute paths (S01); without it nothing is written (S02) |');
L('| outfile | string | NOT honored by the API on 1.4.0: output is a bare ' + BTK + './pure.js' + BTK + ', nothing on disk at the outfile path OR cwd (S19) — type-declared but inert; use ' + BTK + 'compile: { outfile }' + BTK + ' instead (S07d) |');
L('| bytecode | boolean | ' + BTK + 'true' + BTK + ' + ' + BTK + "target: 'bun'" + BTK + ' → an extra ' + BTK + 'bytecode' + BTK + '-kind output ' + BTK + '*.jsc' + BTK + ' alongside the entry (S06: ' + s06.outputs.map((o: any) => o.kind).join(' + ') + ') |');
L('| compile | boolean | CompileTarget | CompileBuildOptions | ' + BTK + 'true' + BTK + ' + outdir → standalone executable written at ' + BTK + 'outdir/<entry>' + BTK + ' (S07a, ' + s07a.observed.onDiskBytes + ' bytes on disk, kind still ' + BTK + 'entry-point' + BTK + '); ' + BTK + "compile: 'bun'" + BTK + ' invalid — target must start ' + BTK + "'bun-'" + BTK + ' (S07b); ' + BTK + 'compile: true' + BTK + ' + outfile IGNORES the outfile: the executable is named after the entry in the entry directory (S07c: ' + BTK + 'pure' + BTK + ' at the fixture root, ~62MB) while ' + BTK + 'compile: { outfile }' + BTK + ' honors it (S07d) |');
L('| target | ' + BTK + "'browser' | 'bun' | 'node'" + BTK + ' | bun emits a ' + BTK + '// @bun' + BTK + ' header + 103B vs 95B for node/browser on the env fixture (S08); node/browser outputs identical for this fixture |');
L('| format | ' + BTK + "'esm' | 'cjs' | 'iife'" + BTK + ' | esm: ' + s('S09-format-esm').outputs[0].size + 'B ' + BTK + 'export {' + BTK + '; cjs: ' + s('S09-format-cjs').outputs[0].size + 'B with ' + BTK + '__defProp' + BTK + ' helpers; iife: ' + s('S09-format-iife').outputs[0].size + 'B ' + BTK + '(() => {' + BTK + ' (S09) |');
L('| minify | boolean | { whitespace?, syntax?, identifiers?, keepNames? } | ' + s('S10-minify-off').outputs[0].size + 'B → ' + s('S10-minify-on').outputs[0].size + 'B; object form { whitespace, identifiers, syntax } == ' + BTK + 'true' + BTK + ' byte-for-byte (S10) |');
L('| sourcemap | ' + BTK + "'none' | 'linked' | 'external' | 'inline' | boolean" + BTK + ' | none: no map (S04-none); linked: .map artifact + ' + BTK + 'sourceMappingURL' + BTK + ' comment (S04-linked); external: .map artifact, NO comment (S04-external); inline: ' + BTK + 'sourcemap: null' + BTK + ', map base64-embedded (S04-inline) |');
L('| naming | string | { entry?, chunk?, asset? } | string form applies to ENTRYPOINTS only (' + s05a.observed.entryPaths.join(', ') + '), chunks keep ' + BTK + '[name]-[hash].[ext]' + BTK + ' (' + s05a.observed.chunkPaths.join(', ') + '); object form applies to all (' + s05b.observed.entryPaths.join(', ') + ' + ' + s05b.observed.chunkPaths.join(', ') + '); hash-less string + multi-output css entry FAILS the build (S05c) |');
L('| external | string[] | ' + BTK + "external: ['zod']" + BTK + ' keeps ' + BTK + 'import { z } from "zod"' + BTK + ' in the output, ' + s15a.observed.size + 'B vs ' + s15b.observed.size + 'B bundled (S15) |');
L('| define | Record<string, string> | ' + BTK + 'define: { MODE: ' + "'prod'" + ' }' + BTK + ' replaces the expression with the literal ' + BTK + '"prod"' + BTK + ' in the output (S11, inlined=true) |');
L('| env | ' + BTK + "'inline' | 'disable' | 'PREFIX_*'" + BTK + ' | NO substitution observed on 1.4.0: ' + BTK + 'process.env.GROUND_MODE' + BTK + ' stays dynamic in all three modes with ' + BTK + 'GROUND_MODE' + BTK + ' set at build time (S12, substituted=false) — use ' + BTK + 'define' + BTK + ' for build-time constants |');
L('| drop | string[] | ' + BTK + "drop: ['console.log']" + BTK + ' removes the call (' + s13a.observed.hasConsoleLog + ' → ' + s13b.observed.hasConsoleLog + ' in output, ' + s13a.outputs[0].size + 'B → ' + s13b.outputs[0].size + 'B, S13) |');
L('| allowUnresolved | string[] | default ' + BTK + "['*']" + BTK + ' lets non-literal ' + BTK + 'import()' + BTK + ' pass through un-bundled (S14-default ok); ' + BTK + '[]' + BTK + ' and a glob allow-list ' + BTK + "['./locales/*.json']" + BTK + ' BOTH fail the build on 1.4.0 for a ' + BTK + '"./locales/" + lang + ".json"' + BTK + ' template (S14-empty/glob) |');
L('| conditions | string[] | string | package.json ' + BTK + 'exports' + BTK + ' conditions honored: local ' + BTK + 'cond-pkg' + BTK + ' resolves ' + BTK + s16a.observed.resolvedMarker + BTK + ' by default and ' + BTK + s16b.observed.resolvedMarker + BTK + ' with ' + BTK + "conditions: ['custom']" + BTK + ' (S16) |');
L('| publicPath | string | asset URLs rewritten in JS: ' + BTK + "'/cdn/pix-6kt9k1q8.png'" + BTK + ' with ' + BTK + "publicPath: '/cdn/'" + BTK + ' (S17, jsReferencesCdn=true) |');
L('| root | string | output structure resolves against root: ' + BTK + 'rooted/app.ts' + BTK + ' → ' + BTK + 'outr2/rooted/app.js' + BTK + ' with root set vs ' + BTK + 'outr/app.js' + BTK + ' without (S18) |');
L();
L('## 3. Corrections vs prior docs claims (§176–§177)');
L();
L('| Prior claim | Verdict | Observed |');
L('|---|---|---|');
L('| ' + BTK + 'BuildArtifact extends Blob, .bytes() available' + BTK + ' | CORRECTED | Blob-CONFORMANT: ' + BTK + 'instanceof Blob' + BTK + ' = false, ' + BTK + '.bytes()' + BTK + ' absent; ' + BTK + '.size/.type/.text()/.arrayBuffer()/.stream()/.json()' + BTK + ' present (S01) |');
L('| ' + BTK + 'hash can be null (hash-less naming)' + BTK + ' | CORRECTED | hash still computed without ' + BTK + '[hash]' + BTK + ' (' + s05a.outputs[0].hash + ', ' + s05a.outputs[1].hash + '); the real ' + BTK + 'null' + BTK + '-ish case is sourcemap artifacts with the ' + BTK + "'00000000'" + BTK + ' placeholder (S04) |');
L('| ' + BTK + "entry-point hash is null by default" + BTK + ' | CORRECTED | present: ' + s01entry.hash + ' (S01) |');
L('| ' + BTK + 'asset gets [name]-[hash].[ext] by default' + BTK + ' | CORRECTED (partial) | file-loader png IS hashed (' + s17.outputs.find((o: any) => o.kind === 'asset').path + '), CSS bundles are NOT (' + s01css.path + ', no hash in name) |');
L('| ' + BTK + 'naming string applies to chunks/assets too' + BTK + ' | CORRECTED | string form: entrypoints only (S05a); object form needed for chunks/assets (S05b) |');
L('| ' + BTK + "env: 'inline' injects env values at build time" + BTK + ' | CORRECTED | no substitution observed on 1.4.0 (S12, all three modes identical output) |');
L('| ' + BTK + 'outfile: single output file' + BTK + ' | CORRECTED | top-level ' + BTK + 'outfile' + BTK + ' is inert on 1.4.0 API — bare-name output, nothing written (S19); ' + BTK + 'compile: { outfile }' + BTK + ' writes (S07d) |');
L('| ' + BTK + 'allowUnresolved: glob list allows dynamic specifiers' + BTK + ' | CORRECTED | only the default ' + BTK + "'*'" + BTK + ' passes through; ' + BTK + '[]' + BTK + ' and glob lists fail the build for this template shape (S14) |');
L('| ' + BTK + 'Response(BuildArtifact) sets ETag' + BTK + ' | CORRECTED (§176) | Content-Type set, Cache-Control and ETag NOT set on 1.4.0 |');
L('| ' + BTK + 'hash-less naming is safe for multi-output builds' + BTK + ' | CORRECTED | ' + BTK + "'static/[name].js'" + BTK + ' + css-importing entry FAILS: ' + BTK + 'Multiple files share the same output path' + BTK + ' (S05c) |');
L('| outdir path semantics (P1/P2) | CONFIRMED | with outdir: absolute written path; without: bare name, nothing written (S01/S02) |');
L('| sourcemap nested artifact (P4) | CONFIRMED | linked/external expose ' + BTK + 'artifact.sourcemap' + BTK + ' as a nested artifact whose ' + BTK + '.text()' + BTK + ' returns map JSON (S04) |');
L('| kind variants (P5) | CONFIRMED | entry-point/chunk/asset/sourcemap/bytecode all observed (S01/S03/S04/S06) |');
L();
L('## 4. Scenario appendix — raw evidence');
L();
for (const sc of ev.scenarios) {
  L('### ' + sc.name + (sc.ok ? '' : ' — build FAILED'));
  L();
  L('Config: ' + configCell(sc.config));
  if (sc.logs && sc.logs.length) { L(); L('Logs: ' + sc.logs.join(' · ')); }
  if (Object.keys(sc.observed).length) { L(); L('Observed: ' + JSON.stringify(sc.observed)); }
  if (sc.outputs.length) {
    L();
    L('| Output path | kind | hash | loader | size | type | sourcemap |');
    L('|---|---|---|---|---|---|---|');
    for (const o of sc.outputs) L(outRow(o));
  }
  L();
}
// ---------- section 5: Blob#image() gotchas (177 refactor) ----------
L('## 5. Blob#image() gotchas — and why BuildArtifact.image() is absent on 1.4.0');
L();
L('bun-types declares ' + BTK + 'BuildArtifact extends Blob' + BTK + ', so the Blob#image()');
L('pipeline would be inherited — but on 1.4.0 the artifact is Blob-CONFORMANT,');
L('NOT a Blob (' + BTK + 'instanceof Blob' + BTK + ' = false, S01) and ' + BTK + '.image()' + BTK + ' is');
L('undefined (evidence buildArtifactImage). The gotchas below are grounded on');
L('the REAL ' + BTK + 'Blob#image()' + BTK + ' / ' + BTK + 'Bun.file().image()' + BTK + ' surface (both present);');
L('they would apply to ' + BTK + 'BuildArtifact.image()' + BTK + ' if Bun ever adds it.');
L();
const ig = ev.imageGotchas;
L('| Gotcha | Verdict | Observed on 1.4.0 |');
L('|---|---|---|');
L('| nothing runs until a terminal (' + BTK + '.bytes()' + BTK + ', ' + BTK + '.write()' + BTK + ', ' + BTK + '.metadata()' + BTK + ') | CONFIRMED | ' + BTK + '.image()' + BTK + ' on a garbage file returns a pipeline without throwing; only the terminal throws (' + BTK + ig.lazy.terminalErrorCode + BTK + ') |');
L('| ' + BTK + 'img.width/height' + BTK + ' are -1 until the first terminal resolves | CONFIRMED | ' + JSON.stringify(ig.dimsBeforeTerminal.before) + ' -> ' + JSON.stringify(ig.dimsBeforeTerminal.after) + ' after ' + BTK + '.resize(8,8).png().bytes()' + BTK + ' |');
L('| HEIC/AVIF macOS/Windows-only (Linux -> ' + BTK + 'ERR_IMAGE_FORMAT_UNSUPPORTED' + BTK + ') | CONFIRMED (platform) | heic encode works on macOS arm64 (image:probe P12); Linux rejection not probeable here (honest pin); bad INPUT uses ' + BTK + 'ERR_IMAGE_UNKNOWN_FORMAT' + BTK + ' / ' + BTK + 'ERR_IMAGE_DECODE_FAILED' + BTK + ' — the unsupported code is platform-only (image:probe P13) |');
L('| format detection by content, not extension/Content-Type | CONFIRMED | ' + BTK + '.jpg' + BTK + ' file with PNG bytes -> ' + BTK + ig.sniffing.jpgFileWithPngBytes + BTK + '; Blob typed ' + BTK + 'image/jpeg' + BTK + ' with PNG bytes -> ' + BTK + ig.sniffing.jpegTypedBlobWithPngBytes + BTK + ' |');
L('| decompression-bomb guard (' + BTK + 'maxPixels' + BTK + ' ~268MP) | CONFIRMED | default ' + ev.imageCtorGotchas.maxPixels.typeDocDefault + ' px (' + BTK + ev.imageCtorGotchas.maxPixels.typeDocDefaultFormula + BTK + '): 16383^2 accepted, 16384^2 -> ' + ev.imageCtorGotchas.maxPixels.boundary.overDefault_16384sq + ' (strict exceeds check); option overrides honored (' + BTK + 'maxPixels: 100' + BTK + ' -> 10x10 ok, 11x11 ' + ev.imageCtorGotchas.maxPixels.boundary.override100_11x11 + ') |');
L('| no format method -> reuses source format, or dest-path extension on ' + BTK + 'write()' + BTK + ' | CONFIRMED | ' + BTK + '.bytes()' + BTK + ' keeps the PNG signature + blob type ' + BTK + ig.formatReuse.noFormatBlobType + BTK + '; ' + BTK + '.write(out.jpg)' + BTK + ' emits JPEG (' + String(ig.formatReuse.writeToJpgPathIsJpeg) + ') |');
L('| ' + BTK + 'new Response(img)' + BTK + ' works; await a terminal in handlers | CONFIRMED (works) | content-type ' + BTK + ig.response.contentType + BTK + ', body ' + ig.response.bodyBytes + 'B; encode-thread timing not directly measured — awaiting a terminal first keeps encode off the JS thread |');
L();

// ---------- section 6: BuildArtifact.slice() gotchas (177 refactor) ----------
L('## 6. BuildArtifact.slice() — returns a plain Blob, with an outdir-dependent negative-offset caveat');
L();
const sg = ev.sliceGotchas;
L('| Gotcha | Verdict | Observed on 1.4.0 |');
L('|---|---|---|');
L('| returns a plain Blob — loses ' + BTK + 'kind/path/loader/hash/sourcemap' + BTK + ' | CONFIRMED | ' + BTK + 'instanceof Blob' + BTK + ' = ' + String(sg.returnsPlainBlob.instanceofBlob) + '; all five props undefined on the slice; the slice GAINS ' + BTK + '.bytes()' + BTK + ' (full Blob surface: ' + Object.keys(sg.returnsPlainBlob.gained).join('/') + ') |');
L('| does not read data immediately — call ' + BTK + '.text()' + BTK + ' / ' + BTK + '.bytes()' + BTK + ' / ' + BTK + '.arrayBuffer()' + BTK + ' | CONFIRMED | slice returns a lazy Blob view; content read on demand; nothing written to disk |');
L('| ' + BTK + 'start/end' + BTK + ' are byte offsets | CONFIRMED | ' + BTK + 'slice(2, 6)' + BTK + ' == content[2:6] (' + JSON.stringify(sg.byteOffsets.slice26Value) + '); ' + BTK + 'slice(0,10)' + BTK + ' matches ' + BTK + 'Blob.prototype.slice(0,10)' + BTK + ' |');
L('| negative values count from the end (per Blob.slice spec) | CORRECTED (outdir-dependent) | WITHOUT ' + BTK + 'outdir' + BTK + ': spec-compliant (' + BTK + 'slice(-4)' + BTK + ' == last 4 bytes). WITH ' + BTK + 'outdir' + BTK + ' on 1.4.0: negative START yields an empty result, negative END is ignored (full remainder) — see the matrix below |');
L('| path: absolute with ' + BTK + 'outdir' + BTK + ', bare output path without; slicing writes nothing | CONFIRMED | ' + (sg.pathSemantics.withOutdirAbsolute ? 'absolute under outdir' : 'non-absolute') + ' vs ' + (sg.pathSemantics.noOutdirBare ? 'bare name' : 'other') + '; slice is in-memory, nothing written |');
L();
L('Negative-offset matrix (content length ' + ev.scenarios.find((x: any) => x.name === 'S01-artifact-surface').outputs.find((o: any) => o.kind === 'entry-point').size + 'B):');
L();
L('| Call | ' + BTK + 'artifact.slice()' + BTK + ' (outdir) | ' + BTK + 'artifact.slice()' + BTK + ' (no outdir) | ' + BTK + 'Blob.slice()' + BTK + ' (spec) |');
L('|---|---|---|---|');
for (const [label, v] of Object.entries(sg.negativeMatrix)) {
  L('| ' + BTK + label + BTK + ' | ' + String((v as any).withOutdir) + ' | ' + String((v as any).noOutdir) + ' | ' + String((v as any).blobSpec) + ' |');
}
L();

// ---------- section 7: Image constructor gotchas (177 refactor) ----------
L('## 7. Bun.Image constructor — inputs, buffer guards, maxPixels, autoOrient');
L();
const icg = ev.imageCtorGotchas;
L('| Gotcha | Verdict | Observed on 1.4.0 |');
L('|---|---|---|');
L('| path strings are FILESYSTEM paths (arbitrary-file-read primitive) | CONFIRMED | ' + BTK + 'new Image(path)' + BTK + ' decodes the file (' + icg.pathIsFilesystemRead.existingPathDecodes + '); a missing path surfaces ' + BTK + icg.pathIsFilesystemRead.missingPathError + BTK + ' directly — pass untrusted bytes as a ' + BTK + 'Buffer' + BTK + '/' + BTK + 'Uint8Array' + BTK + ' instead |');
L('| format is sniffed from bytes, not extension/' + BTK + 'Content-Type' + BTK + ' | CONFIRMED | ' + BTK + '.jpg' + BTK + ' file holding PNG bytes -> ' + icg.formatSniffedFromBytes.jpgNamedFileWithPngBytes + '; raw PNG bytes -> ' + icg.formatSniffedFromBytes.rawPngBytes + ' |');
L('| don\'t mutate/transfer the input buffer while decoding is pending (runs off-thread, borrows bytes) | PARTIAL | ' + BTK + 'Uint8Array' + BTK + ' / ' + BTK + 'ArrayBuffer' + BTK + ' / ' + BTK + 'Buffer' + BTK + ' inputs all accepted; transferring between constructor and terminal -> OBSERVED ' + BTK + icg.bufferGuards.transferredBetweenCtorAndTerminal + BTK + ' (the docs claim ' + BTK + icg.bufferGuards.docClaimsInvalidStateForTransfer + BTK + '); mutation-during-decode timing is not deterministically probeable |');
L('| ' + BTK + 'SharedArrayBuffer' + BTK + ' and resizable buffers rejected | CONFIRMED | both -> ' + BTK + icg.bufferGuards.sharedArrayBuffer + BTK + ' (' + BTK + 'resizable / shared ArrayBuffer is not supported' + BTK + '); pass ' + BTK + 'buf.slice()' + BTK + ' to get a fixed-size view |');
L('| ' + BTK + 'maxPixels' + BTK + ' bomb guard, header-checked before pixel allocation; default ~268MP matches Sharp | CONFIRMED | default ' + icg.maxPixels.typeDocDefault + ' px (' + BTK + icg.maxPixels.typeDocDefaultFormula + BTK + '): 16383^2 accepted, 16384^2 -> ' + icg.maxPixels.boundary.overDefault_16384sq + '; option overrides honored (' + BTK + 'maxPixels: 100' + BTK + ' -> 10x10 ok, 11x11 ' + icg.maxPixels.boundary.override100_11x11 + ') |');
L('| ' + BTK + 'autoOrient' + BTK + ' defaults to ' + BTK + 'true' + BTK + ' (JPEG EXIF orientation applied before other transforms) | CONFIRMED | hand-spliced EXIF ' + BTK + 'Orientation=6' + BTK + ' into a Bun-encoded 2x1 JPEG: default decode -> ' + icg.autoOrient.exifOrientation6Default + ' (rotated), ' + BTK + 'autoOrient: false' + BTK + ' -> ' + icg.autoOrient.exifOrientation6WithFalse + ' (raw); no EXIF -> ' + icg.autoOrient.baseJpegNoExif + ' |');
L();

// ---------- section 8: Prisma Compute image-transformations claims (177 refactor) ----------
L('## 8. Prisma Compute image-transformations guide — claims grounded');
L();
L('Source: https://www.prisma.io/docs/compute/image-transformations (Bun.Image route pattern).');
L('Every Bun.Image claim probed on 1.4.0 — one CORRECTED (S3 access form), one PARTIAL (grayscale).');
L();
const cg = ev.computeGuideGotchas;
L('| Claim | Verdict | Observed on 1.4.0 |');
L('|---|---|---|');
L('| ' + BTK + 'resize(w, h, { withoutEnlargement: true })' + BTK + ' prevents upscaling | CONFIRMED | 2x1 source -> ' + BTK + '800x600' + BTK + ' stays ' + cg.withoutEnlargement.withOptionResult + ' with the option; ' + cg.withoutEnlargement.withoutOptionResult + ' without (exact/stretch) |');
L('| ' + BTK + 'resize(width)' + BTK + ' / ' + BTK + 'resize(width, height)' + BTK + ' / ' + BTK + 'fit: "inside"' + BTK + ' | CONFIRMED | aspect-preserving inside vs exact fill (image:probe P4/P14) |');
L('| ' + BTK + 'resize(width, undefined, { fit, withoutEnlargement, filter })' + BTK + ' helper pattern | CONFIRMED | accepted; ' + cg.resizeWidthUndefined + ' result with ' + BTK + 'withoutEnlargement' + BTK + ' |');
L('| ' + BTK + 'filter' + BTK + ': lanczos3/mitchell/box/nearest (+ bilinear/cubic/lanczos2) | CONFIRMED | all ' + Object.keys(cg.filtersAccepted).length + ' accepted (' + Object.entries(cg.filtersAccepted).filter(([, v]) => v).map(([k]) => k).join(', ') + ') |');
L('| ' + BTK + 'rotate(90/180/270)' + BTK + ', ' + BTK + 'flip()' + BTK + '/' + BTK + 'flop()' + BTK + ' | CONFIRMED | rotate alone swaps dims; rotate/flip/flop AFTER resize are NO-OPS on 1.4.0 (§5 note) |');
L('| ' + BTK + 'modulate({ brightness, saturation })' + BTK + '; saturation 0 = grayscale | PARTIAL | option accepted; 0 vs 1 lossless-webp outputs differ (' + String(cg.saturation.zeroVsOneLosslessBytesDiffer) + '); grayscale not directly verifiable — no pixel-decode API on 1.4.0 |');
L('| ' + BTK + 'jpeg({ quality, progressive })' + BTK + ' | CONFIRMED | ' + BTK + 'progressive: true' + BTK + ' emits a multi-scan JPEG (SOF2 marker found), baseline is SOF0-only |');
L('| ' + BTK + 'png({ compressionLevel })' + BTK + ' / ' + BTK + 'png({ palette, colors, dither })' + BTK + ' | CONFIRMED | ' + BTK + 'palette: true' + BTK + ' emits indexed PNG (IHDR color type ' + cg.palettePng.palette64ColorType + ', plain is ' + cg.palettePng.plainColorType + ') |');
L('| ' + BTK + 'webp({ quality })' + BTK + ' / ' + BTK + 'webp({ lossless: true })' + BTK + ' | CONFIRMED | lossless VP8L vs lossy VP8 magics (image:probe P21) |');
L('| ' + BTK + 'placeholder()' + BTK + ' | CONFIRMED | ThumbHash data: URL (image:probe P8) |');
L('| ' + BTK + 'blob()/bytes()/buffer()' + BTK + ' bodies; ' + BTK + 'write(path)' + BTK + ' / ' + BTK + 'write(Bun.file(...))' + BTK + ' | CONFIRMED | ' + BTK + 'write(Bun.file(out))' + BTK + ' -> ' + cg.writeBunFile.bytes + ' bytes written |');
L('| ' + BTK + 'Bun.s3("key").image()' + BTK + ' / ' + BTK + 'write(Bun.s3("key"))' + BTK + ' | CORRECTED | ' + BTK + 'Bun.s3' + BTK + ' is an ' + BTK + cg.s3.constructorName + BTK + ' INSTANCE (' + cg.s3.callError + '...); the callable form throws — use ' + BTK + 'Bun.s3.file("key").image()' + BTK + '/.write() (both ' + cg.s3.fileImage + ' / ' + cg.s3.fileWrite + ') |');
L('| no crop/extract coordinates exposed | CONFIRMED | ' + BTK + 'crop/extract/composite/extend' + BTK + ' all ' + cg.cropSurface.crop + ' on 1.4.0 — crop needs an external library |');
L('| ' + BTK + 'new Bun.Image(input, { maxPixels, autoOrient })' + BTK + ' + HEIC/AVIF platform-dependence | CONFIRMED | see §7 and §5 |');
L();

await Bun.write(DOC, md.join('\n'));
console.log('build-artifact:findings - regenerated ' + DOC + ' (' + ev.scenarios.length + ' scenarios)');

export {};