#!/usr/bin/env bun
/**
 * bun run coverage:matrix - regenerate docs/BUN_API_COVERAGE.md from
 * the FULL Bun shape (tools/bun-shape.json, §168) + repo usage (§163,
 * §169). Rows = every shape member (top-level + sub-namespace + the
 * FFI extension). Tier A: used runtime members must have a probe gate
 * (hard fail); unused GAPs are reported, not fatal; every GATES key
 * must exist in the shape (dead curated entries fail). Offline.
 */
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const shape = JSON.parse(await Bun.file(join(ROOT, "tools/bun-shape.json")).text());
const BTK = String.fromCharCode(96); // backtick for the markdown table
import { GATES, gateFor } from '../src/lib/bun-gates.ts';



// 1) repo token counts (single rg over the source dirs, depth-2 aware).
const scan = Bun.spawnSync(["rg", "-o", "Bun\.[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)?", "src", "tools", "scripts", "tests", "--no-filename"], { cwd: ROOT, stdout: "pipe" });
const counts: Record<string, number> = {};
const shapeKeys = new Set(shape.members.map((mm: any) => (mm.ns ? mm.ns + "." + mm.name : mm.name)));
for (const l of (scan.stdout?.toString() ?? "").split("\n")) {
  const m = l.match(/Bun\.([A-Za-z_$][A-Za-z0-9_$]*)(?:\.([A-Za-z_$][A-Za-z0-9_$]*))?/);
  if (m) {
    // longest shape-matching key: Bun.argv.includes is usage of argv,
    // Bun.TOML.parse is usage of the TOML.parse member.
    let key = m[1]!;
    if (m[2] && shapeKeys.has(m[1] + "." + m[2])) key = m[1] + "." + m[2];
    counts[key] = (counts[key] ?? 0) + 1;
  }
}
// from "bun" named imports count as member usage too (§175) - the Bun.*
// token scan misses import { $ } from "bun" (44 files do this).
const impScan = Bun.spawnSync(["rg", "-n", "--no-heading", "from \"bun\"", "src", "tools", "scripts", "tests"], { cwd: ROOT, stdout: "pipe" });
const IMP_RE = /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+"bun"/;
for (const l of (impScan.stdout?.toString() ?? "").split("\n")) {
  const m = l.match(IMP_RE);
  if (!m) continue;
  for (const part of m[1].split(",")) {
    const name = part.trim().split(/\s+as\s+/)[0].trim();
    if (name && shapeKeys.has(name)) counts[name] = (counts[name] ?? 0) + 1;
  }
}

// 2) GATES validation: every curated key must exist in the shape.
const shapeTop = new Set(shape.members.filter((m: any) => !m.ns).map((m: any) => m.name));
const shapeNs = new Set(shape.members.filter((m: any) => m.ns).map((m: any) => m.ns));
const deadGates = Object.keys(GATES).filter((k) => !shapeTop.has(k) && !shapeNs.has(k));

// 3) rows from the FULL shape.
interface MatrixRow {
  full: string;
  runtime: string;
  types: string;
  docs: string;
  gate: string;
  uses: number;
  typeOnly: boolean;
}
const rows: MatrixRow[] = shape.members.map((m: any) => {
  const full = m.ns ? m.ns + "." + m.name : m.name;
  const live = !m.typeOnly && (m.ns ? (Bun as any)[m.ns]?.[m.name] !== undefined : (Bun as any)[m.name] !== undefined);
  const gate = gateFor(m);
  return {
    full,
    runtime: m.typeOnly ? "type-only" : live ? typeof (m.ns ? (Bun as any)[m.ns]?.[m.name] : (Bun as any)[m.name]) : "missing",
    types: "y",
    docs: m.docs ? "y" : "n",
    gate,
    uses: counts[full] ?? 0,
    typeOnly: m.typeOnly,
  };
});
rows.sort((a, b) => (a.typeOnly ? 1 : 0) - (b.typeOnly ? 1 : 0) || b.uses - a.uses || a.full.localeCompare(b.full));

const runtimeRows = rows.filter((r) => r.runtime !== "type-only" && r.runtime !== "missing");
const used = runtimeRows.filter((r) => r.uses > 0);
const tierA = used.filter((r) => r.gate === "GAP");
const gaps = runtimeRows.filter((r) => r.gate === "GAP" && r.uses === 0);

const md = [
  "# Bun API Coverage Matrix",
  "",
  "Regenerated by " + BTK + "bun run coverage:matrix" + BTK + " (tools/bun-coverage-matrix.ts, §163).",
  "Rows = the FULL Bun 1.4.0 shape (" + BTK + "tools/bun-shape.json" + BTK + ", §168): module exports,",
  "sub-namespace members, and the FFI extension. GAP = unprobed member (unused,",
  "non-fatal); Tier-A failures (used-but-unprobed) exit nonzero; type-only = types",
  "without a runtime value; missing = declared value absent at runtime.",
  "",
  "| Token | Runtime | Types | Docs | Gate | Uses |",
  "|---|---|---|---|---|---|",
  ...rows.map((x) => "| " + BTK + x.full + BTK + " | " + x.runtime + " | " + x.types + " | " + x.docs + " | " + x.gate + " | " + x.uses + " |"),
  "",
  "**Shape summary:** " + rows.length + " members (" + shape.members.filter((m: any) => !m.ns).length + " top-level, " + shape.members.filter((m: any) => m.ns).length + " sub-namespace) · " + runtimeRows.length + " runtime values · " + (rows.length - runtimeRows.length) + " type-only/missing · " + used.length + " used · " + (used.length - tierA.length) + " probed · " + gaps.length + " unused GAPs" + (tierA.length ? " · TIER-A: " + tierA.map((r) => r.full).join(", ") : "") + (deadGates.length ? " · DEAD GATES KEYS: " + deadGates.join(", ") : ""),
  "",
].join("\n");
await Bun.write(join(ROOT, "docs/BUN_API_COVERAGE.md"), md);

console.log("matrix regenerated: " + rows.length + " rows · " + runtimeRows.length + " runtime · " + used.length + " used (" + (used.length - tierA.length) + " probed) · " + gaps.length + " unused GAPs" + (deadGates.length ? " · dead GATES keys: " + deadGates.join(",") : ""));
if (tierA.length) {
  console.error("TIER-A: used-but-unprobed: " + tierA.map((r) => r.full).join(", "));
}
if (deadGates.length) {
  console.error("DEAD GATES KEYS (not in shape): " + deadGates.join(", "));
}
process.exit(tierA.length === 0 && deadGates.length === 0 ? 0 : 1);

export {};
