#!/usr/bin/env bun
/**
 * `bun run ground` — regenerate the Bun-grounding manifest and its generated
 * doc from the pinned bun-types shape + repo usage + official docs URLs + the
 * probe registry. Offline. See src/lib/ground.ts for the truth hierarchy.
 *
 *   bun run ground          # regen tools/bun-grounding.json + docs/BUN_GROUNDED.md
 *   bun run ground:check    # verify live (freshness, coverage, probes, URLs)
 */
import {
  GROUNDED_DOC_PATH,
  MANIFEST_PATH,
  DOCS_INDEX,
  docsUrlFor,
  findStaleUrls,
  loadShape,
  normalizeGate,
  resolveToken,
  scanBunTokens,
  shapeLookup,
  UNKNOWN_TOKEN_ALLOWLIST,
} from "../src/lib/ground.ts";
import type { GroundManifest, GroundRow } from "../src/lib/ground.ts";
import { gateFor } from "../src/lib/bun-gates.ts";
import { WIRED_GATES } from "./ground-probes/index.ts";

const ROOT = import.meta.dir + "/..";

const shape = await loadShape(ROOT);
const lookup = shapeLookup(shape);
const usage = scanBunTokens(ROOT);

// Resolve each used token to a shape member (longest ns.name, else top-level).
const rowsBySymbol = new Map<string, GroundRow>();
const unknownTokens: string[] = [];
for (const [token, count] of usage) {
  const member = resolveToken(token, lookup);
  if (!member) { if (!UNKNOWN_TOKEN_ALLOWLIST.has(token)) unknownTokens.push(token); continue; }
  const symbol = member.ns ? "Bun." + member.ns + "." + member.name : "Bun." + member.name;
  const existing = rowsBySymbol.get(symbol);
  if (existing) { existing.usageCount += count; continue; }
  const gate = normalizeGate(gateFor(member));
  const runtimeKey = member.ns || member.name;
  const runtime = typeof (Bun as any)[runtimeKey] !== "undefined";
  rowsBySymbol.set(symbol, {
    symbol,
    name: member.name,
    ns: member.ns,
    kind: member.kind,
    typeOnly: member.typeOnly,
    runtime,
    used: true,
    usageCount: count,
    docsUrl: docsUrlFor(member),
    gate,
    probeWired: gate !== "" && WIRED_GATES.includes(gate),
  });
}

const rows = [...rowsBySymbol.values()].sort((a, b) => b.usageCount - a.usageCount);

// Stale-URL audit across the repo source dirs.
const sourceText = await collectSourceText(ROOT);
const stale = findStaleUrls(sourceText);

async function collectSourceText(root: string): Promise<string> {
  const parts: string[] = [];
  for (const dir of ["src", "tools", "scripts"]) {
    const proc = Bun.spawnSync(["rg", "--no-heading", "-i", "bun\\.com/docs", dir], { cwd: root, stdout: "pipe" });
    if (proc.exitCode === 0) parts.push(proc.stdout.toString());
  }
  return parts.join("\n");
}

const manifest: GroundManifest = {
  bunVersion: shape.bunVersion,
  shapeRevision: shape.bunRevision,
  generatedAt: new Date().toISOString(),
  generator: "tools/ground-bun.ts",
  shapeFile: shape.bunVersion + " (" + shape.bunRevision.slice(0, 10) + ")",
  docsIndex: DOCS_INDEX,
  rows,
  unknownTokens: [...new Set(unknownTokens)].sort(),
  staleUrlCount: stale.length,
};

await Bun.write(ROOT + "/" + MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n");

// ── generated doc ────────────────────────────────────────────────────────────
const runtimeRows = rows.filter((r) => r.runtime);
const typeOnlyCount = rows.length - runtimeRows.length;
const rowLines = runtimeRows.map((r) =>
  "| `" + r.symbol + "` | " + r.kind + " | " + (r.typeOnly ? "yes" : "")
  + " | [guide](" + r.docsUrl + ") | " + (r.gate || "—") + " | " + (r.probeWired ? "wired" : "")
  + " | " + r.usageCount + " |",
);
const md: string[] = [
  "# Bun grounding — generated manifest (DO NOT EDIT)",
  "",
  "Generated by `bun run ground` from the **pinned `bun-types@1.4.0` shape",
  "(`tools/bun-shape.json`, TS-compiler-parsed)** + official bun.com docs URLs + the",
  "consolidated probe registry (`tools/ground-probes`). Verify live with",
  "`bun run ground:check` (wired into `bun run check`). Curated deep dives:",
  "Supersedes the retired docs/BUN_API_COVERAGE.md, docs/BUN_MODULE_SHAPE.md and",
  "docs/REPO_API_BUN.md (retired 2026-08-26; git history preserves them).",
  "[`BUN_FILE.md`](BUN_FILE.md), [`BUN_SHELL.md`](BUN_SHELL.md), [`BUN_NATIVE.md`](BUN_NATIVE.md).",
  "",
  "- bun " + shape.bunVersion + " (shape revision `" + shape.bunRevision.slice(0, 10) + "`)",
  "- docs index: " + DOCS_INDEX,
  "- generated: " + manifest.generatedAt,
  "- used symbols: " + rows.length + " (runtime " + runtimeRows.length + ", type-only " + typeOnlyCount + ") · unknown tokens: " + unknownTokens.length + " · stale URLs: " + stale.length,
  "",
  "## Used symbols — runtime surface (" + runtimeRows.length + ")",
  "",
  "Type-only members (" + typeOnlyCount + ") are tracked in tools/bun-grounding.json but excluded here — they are types, not runtime values.",
  "",
  "| Symbol | Kind | TypeOnly | Docs | Gate | Probe | Uses |",
  "| --- | --- | --- | --- | --- | --- | --- |",
  ...rowLines,
  "",
  "## Unknown tokens (not in the pinned shape — investigate)",
  "",
  ...(unknownTokens.length ? unknownTokens.map((t) => "- `" + t + "`") : ["(none)"]),
  "",
  "## Stale-URL audit",
  "",
  ...(stale.length ? stale.map((u) => "- " + u) : ["(clean — no stale bun.com URLs in src/tools/scripts/tests)"]),
  "",
  "## Update flow",
  "",
  "```text",
  "bun run shape:gen      # after a bun-types bump: re-parse the pinned types",
  "bun run ground         # regen this doc + tools/bun-grounding.json",
  "bun run ground:check   # gate: freshness + coverage + probes + URLs",
  "```",
  "",
  "> Probes are runtime assertions on the installed bun (1.4.0); a probe marked",
  "> \"wired\" runs in `ground:check`. Pinned pitfalls (e.g. Bun.Archive BunFile",
  "> 0-byte values, sliced-write ignored) are asserted as negative probes.",
];

await Bun.write(ROOT + "/" + GROUNDED_DOC_PATH, md.join("\n") + "\n");

console.log("ground:", rows.length + " used symbols, " + unknownTokens.length + " unknown, " + stale.length + " stale URLs");
console.log("  -> " + MANIFEST_PATH + " + " + GROUNDED_DOC_PATH);
