#!/usr/bin/env bun
/**
 * bun run module-shape:report - per-module Bun usage, annotated with
 * probe-gate + docs status from the full shape (tools/bun-shape.json,
 * §168) and the gate map (src/lib/bun-gates.ts, §170), plus a REAL
 * code example per token (first matching source line, §173).
 * Regenerates docs/BUN_MODULE_SHAPE.md. Offline.
 */
import { join } from "node:path";
import { gateFor } from "../src/lib/bun-gates.ts";

const ROOT = join(import.meta.dir, "..");
const BTK = String.fromCharCode(96);
const shape = JSON.parse(await Bun.file(join(ROOT, "tools/bun-shape.json")).text());
const byKey = new Map<string, any>();
const shapeTop = new Set<string>();
for (const m of shape.members) {
  byKey.set(m.ns ? m.ns + "." + m.name : m.name, m);
  if (!m.ns) shapeTop.add(m.name);
}

// Per-module usage with line numbers + source text (single rg pass;
// Uses = matching source LINES, example = the first matching line).
const scan = Bun.spawnSync(["rg", "-n", "--no-heading", "Bun\.[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)?", "src", "tools", "scripts", "tests"], { cwd: ROOT, stdout: "pipe" });
const usage = new Map<string, Map<string, { count: number; example: string }>>();
const TOKEN_RE = /Bun\.([A-Za-z_$][A-Za-z0-9_$]*)(?:\.([A-Za-z_$][A-Za-z0-9_$]*))?/g;
for (const l of (scan.stdout?.toString() ?? "").split("\n")) {
  if (!l.includes("Bun.")) continue;
  const c1 = l.indexOf(":");
  if (c1 < 0) continue;
  const c2 = l.indexOf(":", c1 + 1);
  if (c2 < 0) continue;
  const path = l.slice(0, c1);
  const text = l.slice(c2 + 1);
  const seg = path.split("/");
  const module = seg.slice(0, -1).join("/") || seg[0];
  const matches = [...text.matchAll(TOKEN_RE)];
  if (matches.length === 0) continue;
  if (!usage.has(module)) usage.set(module, new Map());
  const mm = usage.get(module)!;
  for (const m of matches) {
    let tok = m[2] ? m[1] + "." + m[2] : m[1];
    // longest shape-matching key: Bun.argv.includes is usage of argv.
    if (tok.includes(".") && !byKey.has(tok)) tok = tok.split(".")[0];
    const cur = mm.get(tok);
    if (cur) cur.count += 1;
    else mm.set(tok, { count: 1, example: text });
  }
}

const liveNames = new Set(Object.keys(Bun));
const clean = (s: string) => {
  const t = s.trim();
  // Keep the Bun. prefix only for LIVE runtime members: placeholder tokens
  // (Bun.Foo, Bun.x) and type-only namespaces (Bun.Security, Bun.ArchiveInput)
  // in quoted source must not reach docs:api STRICT (§173).
  const unp = t
    .replace(/Bun\.([A-Za-z_$][A-Za-z0-9_$]*)/g, (_m, n: string) => (liveNames.has(n) ? "Bun." + n : n))
    // escape markdown image syntax (![alt](src)) so the assets gate does
    // not resolve quoted source as a real image ref (§174)
    .replace(/!\[/g, "!\\[");
  if (unp.length <= 110) return unp.replace(/\|/g, "\\|");
  const cut = unp.slice(0, 110);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 40 ? cut.slice(0, lastSpace) : cut).replace(/\|/g, "\\|") + "...";
};

const modules = [...usage.keys()].sort();
const md: string[] = [
  "# Bun usage by module",
  "",
  "Regenerated by " + BTK + "bun run module-shape:report" + BTK + " (tools/module-shape-report.ts, §170).",
  "Per-module " + BTK + "Bun.*" + BTK + " usage annotated with the probe gate, docs",
  "status, and a REAL code example (first matching source line, §173).",
  "Uses = matching source lines. Gate = GAP means used-but-unprobed (a",
  "Tier-A failure in the matrix). unmapped = prose/placeholder/non-existent",
  "API mentions (e.g. Bun.rename documents non-existence; placeholder",
  "tokens like Foo and x are shown without the Bun. prefix) - review-only.",
  "",
];
for (const mod of modules) {
  const toks = [...usage.get(mod)!.entries()].sort((a, b) => b[1].count - a[1].count);
  md.push("## " + mod);
  md.push("");
  md.push("| Token | Uses | Gate | Docs | Example |");
  md.push("|---|---|---|---|---|");
  for (const [tok, u] of toks) {
    const m = byKey.get(tok);
    const gate = m ? gateFor(m) : "unmapped";
    const docs = m ? (m.docs ? "y" : "n") : "?";
    md.push("| " + BTK + tok + BTK + " | " + u.count + " | " + gate + " | " + docs + " | " + clean(u.example) + " |");
  }
  md.push("");
}
await Bun.write(join(ROOT, "docs/BUN_MODULE_SHAPE.md"), md.join("\n") + "\n");
console.log("module-shape report regenerated: " + modules.length + " modules with code examples");

export {};
