#!/usr/bin/env bun
/**
 * bun run module-shape:report - per-module Bun usage, annotated with
 * probe-gate + docs status from the full shape (tools/bun-shape.json,
 * §168) and the gate map (src/lib/bun-gates.ts, §170). Regenerates
 * docs/BUN_MODULE_SHAPE.md. Offline.
 */
import { join } from "node:path";
import { gateFor } from "../src/lib/bun-gates.ts";

const ROOT = join(import.meta.dir, "..");
const BTK = String.fromCharCode(96);
const shape = JSON.parse(await Bun.file(join(ROOT, "tools/bun-shape.json")).text());
const byKey = new Map<string, any>();
for (const m of shape.members) byKey.set(m.ns ? m.ns + "." + m.name : m.name, m);

// Per-module usage with filenames (single rg pass).
const scan = Bun.spawnSync(["rg", "-o", "--no-heading", "Bun\.[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)?", "src", "tools", "scripts", "tests"], { cwd: ROOT, stdout: "pipe" });
const usage = new Map<string, Map<string, number>>();
for (const l of (scan.stdout?.toString() ?? "").split("\n")) {
  if (!l.includes("Bun.")) continue;
  const ci = l.indexOf(":");
  if (ci < 0) continue; // no path prefix: skip
  const path = l.slice(0, ci);
  let tok = l.slice(ci + 1).replace(/^Bun\./, "");
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*(\.[A-Za-z_$][A-Za-z0-9_$]*)?$/.test(tok)) continue; // mangled match
  // longest shape-matching key: Bun.argv.includes is usage of argv.
  if (tok.includes(".") && !byKey.has(tok)) tok = tok.split(".")[0];
  const seg = path.split("/");
  const module = seg.slice(0, -1).join("/") || seg[0];
  if (!usage.has(module)) usage.set(module, new Map());
  const mm = usage.get(module)!;
  mm.set(tok, (mm.get(tok) ?? 0) + 1);
}

const modules = [...usage.keys()].sort();
const md: string[] = [
  "# Bun usage by module",
  "",
  "Regenerated by " + BTK + "bun run module-shape:report" + BTK + " (tools/module-shape-report.ts, §170).",
  "Per-module " + BTK + "Bun.*" + BTK + " usage annotated with the probe gate and docs",
  "status from the full shape (" + BTK + "tools/bun-shape.json" + BTK + ", §168).",
  "Gate = GAP means used-but-unprobed (a Tier-A failure in the matrix).",
  "unmapped = prose/placeholder/non-existent-API mentions (e.g. Bun.rename",
  "documents non-existence; placeholder tokens like Foo and x are shown",
  "without the Bun. prefix) - review-only.",
  "",
];
for (const mod of modules) {
  const toks = [...usage.get(mod)!.entries()].sort((a, b) => b[1] - a[1]);
  md.push("## " + mod);
  md.push("");
  md.push("| Token | Uses | Gate | Docs |");
  md.push("|---|---|---|---|");
  for (const [tok, c] of toks) {
    const m = byKey.get(tok);
    const gate = m ? gateFor(m) : "unmapped";
    const docs = m ? (m.docs ? "y" : "n") : "?";
    md.push("| " + BTK + tok + BTK + " | " + c + " | " + gate + " | " + docs + " |");
  }
  md.push("");
}
await Bun.write(join(ROOT, "docs/BUN_MODULE_SHAPE.md"), md.join("\n") + "\n");
console.log("module-shape report regenerated: " + modules.length + " modules -> docs/BUN_MODULE_SHAPE.md");

export {};
