#!/usr/bin/env bun
/**
 * scratch:docs - regenerate scratch/README.md as an accurate index of the
 * probe/fixture scratchpad, and (--check) verify it is not stale.
 */
import { readdirSync, statSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename, extname } from 'node:path';
import { parseArgs } from 'node:util';

const ROOT = join(import.meta.dir, '..');
const SCRATCH = join(ROOT, 'scratch');
const README = join(SCRATCH, 'README.md');

export const REFERENCE_FILES: string[] = [
  'tools/build-artifact-evidence.ts',
  'tools/build-artifact-findings.ts',
  'tools/reference-cross-check/run.ts',
  'tools/reference-cross-check/compare.ts',
  'tools/reference-cross-check/evidence-loader.ts',
  'tools/reference-cross-check/docs-parser.ts',
  'tools/verify-contracts.ts',
  'tests/lib/bun-markdown-coverage.test.ts',
  'docs/BUN_BUILD_FINDINGS.md',
  'docs/AGENT-PITFALLS.md',
];

export type Kind = 'probe' | 'log' | 'cert' | 'output' | 'other';

export function classify(name: string): Kind {
  const e = extname(name).toLowerCase();
  if (e === '.ts' || e === '.mjs' || e === '.js') return 'probe';
  if (e === '.log') return 'log';
  if (e === '.pem') return 'cert';
  if (e === '.txt' || e === '.md' || e === '.json' || e === '.out') return 'output';
  return 'other';
}
export interface Entry {
  name: string;
  kind: Kind;
  bytes: number;
  orphaned: boolean;
}

export function isOrphaned(name: string): boolean {
  const needle = name.replace(/\.(ts|mjs|js|log|txt|md|json|out|pem)$/i, '');
  if (needle.length < 4) return false; // too generic to judge
  const refs = REFERENCE_FILES.map((f) => readFileSync(join(ROOT, f), 'utf8'));
  return !refs.some((t) => t.includes(needle));
}

export function scan(): { entries: Entry[]; dirs: { name: string; count: number; bytes: number }[] } {
  const names = readdirSync(SCRATCH).filter((n) => n !== 'README.md' && n !== '.stale');
  const entries: Entry[] = [];
  const dirs: { name: string; count: number; bytes: number }[] = [];
  for (const n of names.sort()) {
    const st = statSync(join(SCRATCH, n));
    if (st.isDirectory()) {
      let count = 0;
      let bytes = 0;
      const walk = (dir: string): void => {
        for (const c of readdirSync(dir)) {
          const pth = join(dir, c);
          const s2 = statSync(pth);
          if (s2.isDirectory()) walk(pth);
          else { count++; bytes += s2.size; }
        }
      };
      walk(join(SCRATCH, n));
      dirs.push({ name: n, count, bytes });
    } else {
      entries.push({ name: n, kind: classify(n), bytes: st.size, orphaned: isOrphaned(n) });
    }
  }
  return { entries, dirs };
}
export function generate(): string {
  const { entries, dirs } = scan();
  const counts: Record<Kind, number> = { probe: 0, log: 0, cert: 0, output: 0, other: 0 };
  for (const e of entries) counts[e.kind]++;
  const orphans = entries.filter((e) => e.orphaned);
  // Dir counts/bytes are NOT rendered: probe gates write into scratch/art-ground
  // DURING parallel verify:contracts runs, which would drift the README (181).
  // Only the top-level FILE list and dir NAMES are stable across gate runs.
  const totalBytes = entries.reduce((a, e) => a + e.bytes, 0);
  const out: string[] = [];
  out.push('# scratch/ — probe & fixture scratchpad (git-ignored, never commit)');
  out.push('');
  out.push('Auto-index regenerated by `bun run scratch:docs` (tools/scratch-docs.ts).');
  out.push('Do not hand-edit this file — the `scratch:docs` verify gate (verify:contracts #57)');
  out.push('fails on drift: run `bun run scratch:docs` after adding/removing scratch files.');
  out.push('Archive dead probes with `bun run scratch:sweep --apply` (moves untouched >45d');
  out.push('orphaned probe/log files into scratch/.stale/).');
  out.push('');
  out.push('## Layout');
  out.push('');
  out.push('- probe scripts (top-level .ts/.mjs/.js): ' + counts.probe);
  out.push('- logs (.log): ' + counts.log);
  out.push('- test certs (.pem): ' + counts.cert);
  out.push('- outputs (.txt/.md/.json/.out): ' + counts.output);
  out.push('- other: ' + counts.other);
  out.push('- fixture directories: ' + dirs.length);
  out.push('- total scratch bytes: ' + totalBytes);
  out.push('');
  if (entries.length > 0) {
    out.push('## Top-level files');
    out.push('');
    out.push('| file | kind | bytes | orphaned |');
    out.push('|---|---|---|---|');
    for (const e of entries) {
      out.push('| ' + e.name + ' | ' + e.kind + ' | ' + e.bytes + ' | ' + (e.orphaned ? 'YES' : '') + ' |');
    }
    out.push('');
  }
  if (dirs.length > 0) {
    out.push('## Fixture directories');
    out.push('');
    out.push('| dir |');
    out.push('|---|');
    for (const d of dirs) out.push('| ' + d.name + '/ |');
    out.push('');
  }
  if (orphans.length > 0) {
    out.push('## Orphaned (not referenced by committed code/docs — sweep candidates)');
    out.push('');
    for (const o of orphans) out.push('- ' + o.name + ' (' + o.kind + ', ' + o.bytes + ' B)');
    out.push('');
  }
  return out.join('\n') + '\n';
}
function main(): number {
  const { values: sv } = parseArgs({ args: Bun.argv.slice(2), options: { check: { type: 'boolean' } }, strict: false, allowPositionals: true });
const check = sv.check === true;
  mkdirSync(SCRATCH, { recursive: true });
  const content = generate();
  let onDisk: string | null = null;
  try { onDisk = readFileSync(README, 'utf8'); } catch { onDisk = null; }
  if (check) {
    if (onDisk === null) {
      writeFileSync(README, content);
      console.log('scratch:docs — README missing, bootstrapped (run again to confirm stable)');
      return 0;
    }
    if (onDisk !== content) {
      console.log('scratch:docs FAIL — scratch/README.md is stale; run `bun run scratch:docs`');
      return 1;
    }
    console.log('scratch:docs — README current (' + entriesCount(content) + ' files indexed)');
    return 0;
  }
  writeFileSync(README, content);
  console.log('scratch:docs — wrote scratch/README.md (' + entriesCount(content) + ' files indexed)');
  return 0;
}

function entriesCount(content: string): number {
  const m = content.match(/\| [^|]+ \| (?:probe|log|cert|output|other) \| \d+ \|/g);
  return m ? m.length : 0;
}

if (import.meta.main) process.exit(main());
