#!/usr/bin/env bun
/**
 * bun run type-drift:probe - types-vs-runtime drift (§159): every
 * runtime Bun member must be mapped in the committed full-shape file
 * (tools/bun-shape.json, §168/§169), and the documented non-existence
 * set stays absent. Structural - consumes the shape generated by
 * tools/bun-shape.ts instead of regex-scanning the dts.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const results: { name: string; pass: boolean; detail: string }[] = [];
const check = (name: string, pass: boolean, detail = "") => { results.push({ name, pass, detail }); console.log((pass ? "PASS" : "FAIL") + "  " + name + (detail ? "  - " + detail : "")); };

const shape = JSON.parse(readFileSync(join(ROOT, "tools/bun-shape.json"), "utf8"));

// P1: every runtime member has a shape entry (structural).
const shapeNames = new Set(shape.members.filter((m: any) => !m.ns).map((m: any) => m.name));
const members = Object.keys(Bun).sort();
const untyped = members.filter((m) => !shapeNames.has(m));
check("P1 every runtime member is mapped in the shape", untyped.length === 0, untyped.join(",") || "all " + members.length + " mapped");

// P2: the readableStreamTo family is declared in the DEPRECATED types
// file (a deprecation signal - still functional in 1.4.0).
const deprecatedMarked = shape.members.filter((m: any) => m.deprecated && m.name.startsWith("readableStreamTo")).map((m: any) => m.name);
check("P2 readableStreamTo* declared deprecated", deprecatedMarked.length >= 2, deprecatedMarked.join(",") + " (still functional - surface:probe P4)");

// P3: documented non-existence set is still absent at runtime.
const absent = ["gzip", "html", "image", "watch", "zstd", "term", "rename", "CSV", "Quic"].filter((m) => (Bun as any)[m] !== undefined);
check("P3 documented non-existences stay absent", absent.length === 0, absent.join(",") || "all absent");

const failed = results.filter((r) => !r.pass);
console.log("type-drift:probe - " + (results.length - failed.length) + "/" + results.length + " checks" + (failed.length ? " FAIL: " + failed.map((f) => f.name).join(", ") : ""));
process.exit(failed.length === 0 ? 0 : 1);

export {};
